### ISSUE TITLE
Writing GIF images with transparency

### ISSUE THREAD

**Issue by NieDzejkob** [imageio/imageio#360] opened 2018-07-07 20:46 UTC
When passing ~~numpy arrays with 4 as the last dimension~~ RGBA PNG images read with `imageio.imread('image.png', format='PNG-PIL')`, `imageio.mimwrite('file.gif', frames,  format='GIF-PIL')`, the transparency channel is being ignored. Is there a way I can output transparent pixels in GIF images with imageio?

**Comment by almarklein** [comment] 2018-07-09 07:42
For clarity, this is about animated GIF, correct?

There is an, apparently yet undocumented argument for the `GIF-PIL` plugin, that might affect transparency:

``py
imageio.mimwrite('file.gif', frames, format='GIF-PIL', quantizer=0)
```

Can you try with values of 0, 1, 2? My guess is that it might work with 2. Please let me know the result, so that I can update the docs - or feel free to submit a PR to update the docs [here](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillowmulti.py#L20).

**Comment by NieDzejkob** [comment] 2018-07-09 08:43
Yes, this is about animated GIF.
Unfortunately, all values of quantizer look the same. Except for `'nq'`, which unsurprisingly throws a `'NoneType' is not callable` TypeError.

**Comment by NieDzejkob** [comment] 2018-07-09 08:48
After looking around the code, [this line](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillowmulti.py#L291) caught my attention. I'll try to find the relevant specification...

**Comment by almarklein** [comment] 2018-07-10 08:36
> I'll try to find the relevant specification...

Please let me know what you find; I have yet to find a good spec for GIF. If we ever find one, it might be worth considering rolling our own complete implementation of GIF, because the interaction with Pillow has also been flaky at times.

**Comment by NieDzejkob** [comment] 2018-07-11 14:00
While not a specification in itself (and I've even spotted a mild inaccuracy with regards to the clear code in compression), [this document](http://www.matthewflickinger.com/lab/whatsinagif) should give you enough background that reading the [W3C specification](https://www.w3.org/Graphics/GIF/spec-gif89a.txt) shouldn't be a problem. I *might* make a PR with a new GIF writer, but I have no idea how the quantization part works. Do you think we should leverage PIL for that or roll our own too?

**Comment by almarklein** [comment] 2018-07-11 19:05
> but I have no idea how the quantization part works. Do you think we should leverage PIL for that or roll our own too?

Good point, a pure-Python quantizer would be slow. I do have the Neuquant algorithm lying around somewhere, which is a great, but slow. So yeah, if we can make use of Pillow for that, that would make things a lot easier/faster.

**Comment by xmubingo** [comment] 2019-06-17 13:42
any update???

**Comment by xmubingo** [comment] 2019-06-17 13:47
> When passing ~numpy arrays with 4 as the last dimension~ RGBA PNG images read with `imageio.imread('image.png', format='PNG-PIL')`, `imageio.mimwrite('file.gif', frames, format='GIF-PIL')`, the transparency channel is being ignored. Is there a way I can output transparent pixels in GIF images with imageio?

did you solve your problem?

**Comment by JieJiSS** [comment] 2019-10-20 14:16
any update?

**Comment by xjcl** [comment] 2020-01-14 06:06
Any update? I need this and would hate to throw away all my code and start over with a different library (suggestions?) :-(

**Comment by almarklein** [comment] 2020-02-18 21:48
Actually,  #220 might be a better idea ...

**Comment by FirefoxMetzger** [comment] 2021-06-19 12:38
@almarklein This issue makes me think of two things:

1. There is constant development of the GIF plugin over at pillow. I remember filing an issue for reading transparent pixels that has since been fixed; perhaps the writing has improved as well? In this case our new pillow plugin should be able to handle transparency in GIFs just fine. However, I can't really test this without a MWE.
2. The legacy pillow plugin has some custom quantization for GIF writing. We didn't port it to the new pillow plugin and wanted to make it into a dedicated GIF writer (since it does some compression, which afaik pillow didn't do at that time). Could this issue be related to it?

**Comment by almarklein** [comment] 2021-06-21 09:12
Yeah, it would be good to try rewriting it relying on Pillow more. Or via ffmpeg, which may even be easier.

**Comment by xjcl** [comment] 2021-06-21 18:42
For anyone curious, for [my use case](https://github.com/xjcl/hugbot/blob/3bdd2d334281bdc7f6e41881cb92031604758bbe/hugify.py#L154) I use a `PIL.Image` with the `append_images` option for writing GIF images with or without transparency. I still use `imageio` for loading the GIF images though.

**Comment by FirefoxMetzger** [comment] 2021-06-22 05:14
@xjcl That's interesting. As far as I understand, the issue here is related to writing GIF with our pillow wrapper, so if pillow now correctly supports writing GIF with transparency, it means that we should support this as well. 

If not, this is a bug that we can easily track down and fix once somebody shares code that reproduces the broken behavior.

**Comment by FirefoxMetzger** [comment] 2021-11-07 14:46
The issue seems to be fixed by the v3 pillow plugin:

```python
import imageio as iio

frames = iio.v3.imread("https://i.stack.imgur.com/022Fl.gif", plugin="pillow", mode="RGBA")
iio.v3.imwrite("transparent.gif", frames, plugin="pillow", mode="RGBA", duration=int(1/25*1000), loop=0, transparency=0)

# note: each frame sets transparent pixels to (0, 255, 0, 0) which is green.
iio.v3.imwrite("opaque.gif", frames[..., :3], plugin="pillow", mode="RGB", duration=int(1/25*1000), loop=0)
```

Writing transparent pixels:
![transparent](https://user-images.githubusercontent.com/4402489/140649555-d7a94b34-6cd3-4521-a9ae-eeda71a62b77.gif)

Writing without alpha channel:
![opaque](https://user-images.githubusercontent.com/4402489/140649629-4c37e8c9-0436-433f-8a8e-fbfdd8fe01c0.gif)


The white/beige marks in the gifs come from the actual frame data, because this particular gif paints over the previous frame using white instead of setting the appropriate disposal method (I couldn't find a better GIF to demonstrate). 

I will go ahead and close this issue but feel free to leave a comment or open a new issue if this persists.

**Closed by FirefoxMetzger** 2021-11-07 14:46 UTC
Labels: type: enhancement, plugin: pillow

**Comment by Purkialo** [comment] 2022-01-13 14:55
> The issue seems to be fixed by the v3 pillow plugin:
> 
> ```python
> import imageio as iio
> 
> frames = iio.v3.imread("https://i.stack.imgur.com/022Fl.gif", plugin="pillow", mode="RGBA")
> iio.v3.imwrite("transparent.gif", frames, plugin="pillow", mode="RGBA", duration=int(1/25*1000), loop=0, transparency=0)
> 
> # note: each frame sets transparent pixels to (0, 255, 0, 0) which is green.
> iio.v3.imwrite("opaque.gif", frames[..., :3], plugin="pillow", mode="RGB", duration=int(1/25*1000), loop=0)
> ```
> 
> Writing transparent pixels: ![transparent](https://user-images.githubusercontent.com/4402489/140649555-d7a94b34-6cd3-4521-a9ae-eeda71a62b77.gif)
> 
> Writing without alpha channel: ![opaque](https://user-images.githubusercontent.com/4402489/140649629-4c37e8c9-0436-433f-8a8e-fbfdd8fe01c0.gif)
> 
> The white/beige marks in the gifs come from the actual frame data, because this particular gif paints over the previous frame using white instead of setting the appropriate disposal method (I couldn't find a better GIF to demonstrate).
> 
> I will go ahead and close this issue but feel free to leave a comment or open a new issue if this persists.

But I got this strange results with the same code...
![456](https://user-images.githubusercontent.com/34876972/149352983-2d99ea11-c658-4186-a787-1de61198b197.gif)
![transparent](https://user-images.githubusercontent.com/34876972/149353078-47e888fa-e7c7-4d3f-ab8e-748efc1b661e.gif)

**Comment by Purkialo** [comment] 2022-01-13 15:23
> > The issue seems to be fixed by the v3 pillow plugin:
> > ```python
> > import imageio as iio
> > 
> > frames = iio.v3.imread("https://i.stack.imgur.com/022Fl.gif", plugin="pillow", mode="RGBA")
> > iio.v3.imwrite("transparent.gif", frames, plugin="pillow", mode="RGBA", duration=int(1/25*1000), loop=0, transparency=0)
> > 
> > # note: each frame sets transparent pixels to (0, 255, 0, 0) which is green.
> > iio.v3.imwrite("opaque.gif", frames[..., :3], plugin="pillow", mode="RGB", duration=int(1/25*1000), loop=0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Writing transparent pixels: ![transparent](https://user-images.githubusercontent.com/4402489/140649555-d7a94b34-6cd3-4521-a9ae-eeda71a62b77.gif)
> > Writing without alpha channel: ![opaque](https://user-images.githubusercontent.com/4402489/140649629-4c37e8c9-0436-433f-8a8e-fbfdd8fe01c0.gif)
> > The white/beige marks in the gifs come from the actual frame data, because this particular gif paints over the previous frame using white instead of setting the appropriate disposal method (I couldn't find a better GIF to demonstrate).
> > I will go ahead and close this issue but feel free to leave a comment or open a new issue if this persists.
> 
> But I got this strange results with the same code... ![456](https://user-images.githubusercontent.com/34876972/149352983-2d99ea11-c658-4186-a787-1de61198b197.gif) ![transparent](https://user-images.githubusercontent.com/34876972/149353078-47e888fa-e7c7-4d3f-ab8e-748efc1b661e.gif)

ok, the parameter 'disposal' solve the problem.
