### ISSUE TITLE
Transparency not working on gifs

### ISSUE THREAD

**Issue by CaptainNichols** [imageio/imageio#1015] opened 2023-07-04 11:49 UTC
I am working on this project and i want gifs to appear, but the alpha on the gif doesn't work , instead of its color being invisible its yellow for the first frame of any and all gifs, here is my code:
from pygame import *
from pygame.locals import *
import imageio
import numpy as np
from PIL import Image
from moviepy.editor import VideoFileClip

FPS=60
init()
width, height = 1200, 600
window_size=(width,height)
character_selection_character_size=(300,300)
screen = display.set_mode((width, height))

class GIFBackground:
    def __init__(self, gif_path, window_size, frame_delay):
        self.gif_frames = self.load_gif_frames(gif_path)
        self.resized_frames = self.resize_frames(window_size)
        self.frame_index = 0
        self.frame_delay = frame_delay
        self.frame_countdown = frame_delay

    def load_gif_frames(self, gif_path):
        return imageio.mimread(gif_path)

    def resize_frames(self, window_size):
        resized_frames = []
        for frame in self.gif_frames:
            pil_image = Image.fromarray(frame)
            resized_frame = pil_image.resize(window_size, Image.ANTIALIAS)
            resized_frames.append(resized_frame)
        return resized_frames

    def update_frame(self):
        self.frame_countdown -= 1
        if self.frame_countdown <= 0:
            self.frame_index = (self.frame_index + 1) % len(self.resized_frames)
            self.frame_countdown = self.frame_delay

    def get_current_frame(self):
        frame = self.resized_frames[self.frame_index]
        self.update_frame()
        return frame

def check_collision_and_click(rect1, rect2):
    mouse_pos = mouse.get_pos()
    if rect1.collidepoint(mouse_pos) and rect2.collidepoint(mouse_pos) and mouse.get_pressed()[0]:
        return True
    else:
        return False

image1 =  image.load("gif/gifR/pixil-frame-1.png")
image2 =  image.load("gif/gifR/pixil-frame-1.png")

GUI_Wood= image.load("Backgrounds/GUI_wood_edit_7.png")
GUI_CharacterSelection=image.load("Backgrounds/Character selection.png")

Arrow_L=  image.load("GuiThings/arrowL.png")
Arrow_R=  image.load("GuiThings/arrowR.png")

GUI_Wood=transform.scale(GUI_Wood, (width,height))
GUI_CharacterSelection=transform.scale(GUI_CharacterSelection, (width,height))

Arrow_R=transform.scale(Arrow_R,(75,75))
Arrow_L=transform.scale(Arrow_L,(75,75))

size_sel_p1=(150,100)

Background_x=0
Background_y=0

Arrow_R_rect = Arrow_R.get_rect()
Arrow_L_rect = Arrow_L.get_rect()
Gui_Wood_rect=GUI_Wood.get_rect()

Arrow_R_x=1000
Arrow_R_y=275

Arrow_L_x=100
Arrow_L_y=275

part1_rect_slot_1 = Rect(294,185,150,100)
part1_rect_slot_2 = Rect(510,185,150,100)
part1_rect_slot_3 = Rect(728,185,150,100)
part1_rect_slot_4 = Rect(294,340,150,100)
part1_rect_slot_5 = Rect(510,340,150,100)
part1_rect_slot_6 = Rect(728,340,150,100)

Arrow_R_rect.x, Arrow_R_rect.y = Arrow_R_x,Arrow_L_y
Arrow_L_rect.x, Arrow_L_rect.y = Arrow_L_x,Arrow_L_y
Gui_Wood_rect.x ,Gui_Wood_rect.y = Background_x,Background_y

Apolalipse_Background_path =      "backgrounds/Apolalipse Background.gif"
Expencive_House_Background_path = "backgrounds/Expencive House Background.gif"
Factory_Background_path =          "backgrounds/Factory Background.gif"
Inside_Of_A_Ship_Background_path = "backgrounds/Inside Of A Ship Background.gif"
Log_Home_In_Fire_Background_path = "backgrounds/Log Home In Fire Background.gif"
Night_WaterFall_Background_path =  "backgrounds/Night WaterFall Background.gif"
RainFall_Background_path =         "backgrounds/RainFall Background.gif"
Tywan_Background_path =            "backgrounds/Tywan Background.gif"
Under_Water_City_Background_path = "backgrounds/Under Water City Background.gif"
Waterfall_Background_path =        "backgrounds/Waterfall background.gif"

Apolalipse_Background_GIF =              GIFBackground(Apolalipse_Background_path, window_size, frame_delay=5)  
Expencive_House_Background_GIF =         GIFBackground(Expencive_House_Background_path, window_size, frame_delay=10)  
Factory_Background_GIF =                 GIFBackground(Factory_Background_path, window_size, frame_delay=1)  
Inside_Of_A_Ship_Background_GIF =        GIFBackground(Inside_Of_A_Ship_Background_path, window_size, frame_delay=3)  
Log_Home_In_Fire_Background_GIF =        GIFBackground(Log_Home_In_Fire_Background_path, window_size, frame_delay=8)  
Night_WaterFall_Background_GIF =         GIFBackground(Night_WaterFall_Background_path, window_size, frame_delay=4)  
RainFall_Background_GIF =                GIFBackground(RainFall_Background_path, window_size, frame_delay=5)  
Tywan_Background_GIF =                   GIFBackground(Tywan_Background_path, window_size, frame_delay=4)  
Under_Water_City_Background_GIF =        GIFBackground(Under_Water_City_Background_path, window_size, frame_delay=3)  
Waterfall_Background_GIF =               GIFBackground(Waterfall_Background_path, window_size, frame_delay=4) 

Apolalipse_Background_GIF_mini =         GIFBackground(Apolalipse_Background_path,size_sel_p1, frame_delay=5)  
Expencive_House_Background_GIF_mini =    GIFBackground(Expencive_House_Background_path,size_sel_p1, frame_delay=10)  
Factory_Background_GIF_mini =            GIFBackground(Factory_Background_path,size_sel_p1, frame_delay=1)  
Inside_Of_A_Ship_Background_GIF_mini =   GIFBackground(Inside_Of_A_Ship_Background_path,size_sel_p1, frame_delay=3)  
Log_Home_In_Fire_Background_GIF_mini =   GIFBackground(Log_Home_In_Fire_Background_path,size_sel_p1, frame_delay=8)  
Night_WaterFall_Background_GIF_mini =    GIFBackground(Night_WaterFall_Background_path,size_sel_p1, frame_delay=10)  
RainFall_Background_GIF_mini =           GIFBackground(RainFall_Background_path,size_sel_p1, frame_delay=5)  
Tywan_Background_GIF_mini =              GIFBackground(Tywan_Background_path,size_sel_p1, frame_delay=4)  
Under_Water_City_Background_GIF_mini =   GIFBackground(Under_Water_City_Background_path,size_sel_p1, frame_delay=3)  
Waterfall_Background_GIF_mini =          GIFBackground(Waterfall_Background_path,size_sel_p1, frame_delay=4) 

clock = time.Clock()

selected_background=""
selection_character = "BigWarrior"
selection_character_path =  "VideoGameCharacters/"+selection_character+"/Stand.gif"
selection_character_GIF =   GIFBackground(selection_character_path, character_selection_character_size, frame_delay=5)
back_ground_selection=1
character_selection_character=1
uniq_char=10
cd=0
PART=1

game_over = False
while not game_over:
    for e in event.get():
        if e.type == QUIT:
            game_over = True

    mouse_pos = mouse.get_pos()
    mouse_x = mouse_pos[0]
    mouse_y = mouse_pos[1]
    mouse_rect = Rect(mouse_x - 15, mouse_y - 15, 40, 40)  

    if PART==1:
        screen.blit(GUI_Wood, (Background_x, Background_y))
        screen.blit(Arrow_L, (100,275))
        screen.blit(Arrow_R, (1000,275))

        if cd < 501:
            cd = cd + 1
        if back_ground_selection==1:
            Apolalipse_Background_GIF_frame_mini = Apolalipse_Background_GIF_mini.get_current_frame()
            Apolalipse_Background_GIF_frame_surface_mini = image.fromstring(Apolalipse_Background_GIF_frame_mini.tobytes(), Apolalipse_Background_GIF_frame_mini.size, Apolalipse_Background_GIF_frame_mini.mode)
            Apolalipse_Background_GIF_frame_surface_mini = transform.scale(Apolalipse_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Apolalipse_Background_GIF_frame_surface_mini, (294, 185))
            if check_collision_and_click(part1_rect_slot_1, mouse_rect):
                selected_background=Apolalipse_Background_GIF                
                PART=2
            Expencive_House_Background_GIF_frame_mini = Expencive_House_Background_GIF_mini.get_current_frame()
            Expencive_House_Background_GIF_frame_surface_mini = image.fromstring(Expencive_House_Background_GIF_frame_mini.tobytes(), Expencive_House_Background_GIF_frame_mini.size, Expencive_House_Background_GIF_frame_mini.mode)
            Expencive_House_Background_GIF_frame_surface_mini = transform.scale(Expencive_House_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Expencive_House_Background_GIF_frame_surface_mini, (510, 185))
            if check_collision_and_click(part1_rect_slot_2, mouse_rect):
                selected_background=Expencive_House_Background_GIF
                PART=2
            Factory_Background_GIF_frame_mini = Factory_Background_GIF_mini.get_current_frame()
            Factory_Background_GIF_frame_surface_mini = image.fromstring(Factory_Background_GIF_frame_mini.tobytes(), Factory_Background_GIF_frame_mini.size, Factory_Background_GIF_frame_mini.mode)
            Factory_Background_GIF_frame_surface_mini = transform.scale(Factory_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Factory_Background_GIF_frame_surface_mini, (728, 185))
            if check_collision_and_click(part1_rect_slot_3, mouse_rect):
                selected_background=Factory_Background_GIF
                PART=2
            Inside_Of_A_Ship_Background_GIF_frame_mini = Inside_Of_A_Ship_Background_GIF_mini.get_current_frame()
            Inside_Of_A_Ship_Background_GIF_frame_surface_mini = image.fromstring(Inside_Of_A_Ship_Background_GIF_frame_mini.tobytes(), Inside_Of_A_Ship_Background_GIF_frame_mini.size, Inside_Of_A_Ship_Background_GIF_frame_mini.mode)
            Inside_Of_A_Ship_Background_GIF_frame_surface_mini = transform.scale(Inside_Of_A_Ship_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Inside_Of_A_Ship_Background_GIF_frame_surface_mini, (294, 340))
            if check_collision_and_click(part1_rect_slot_4, mouse_rect):
                selected_background=Inside_Of_A_Ship_Background_GIF
                PART=2
            Log_Home_In_Fire_Background_GIF_frame_mini = Log_Home_In_Fire_Background_GIF_mini.get_current_frame()
            Log_Home_In_Fire_Background_GIF_frame_surface_mini = image.fromstring(Log_Home_In_Fire_Background_GIF_frame_mini.tobytes(), Log_Home_In_Fire_Background_GIF_frame_mini.size, Log_Home_In_Fire_Background_GIF_frame_mini.mode)
            Log_Home_In_Fire_Background_GIF_frame_surface_mini = transform.scale(Log_Home_In_Fire_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Log_Home_In_Fire_Background_GIF_frame_surface_mini, (510, 340))
            if check_collision_and_click(part1_rect_slot_5, mouse_rect):
                selected_background=Log_Home_In_Fire_Background_GIF
                PART=2
            Night_WaterFall_Background_GIF_frame_mini = Night_WaterFall_Background_GIF_mini.get_current_frame()
            Night_WaterFall_Background_GIF_frame_surface_mini = image.fromstring(Night_WaterFall_Background_GIF_frame_mini.tobytes(), Night_WaterFall_Background_GIF_frame_mini.size, Night_WaterFall_Background_GIF_frame_mini.mode)
            Night_WaterFall_Background_GIF_frame_surface_mini = transform.scale(Night_WaterFall_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Night_WaterFall_Background_GIF_frame_surface_mini, (728, 340))
            if check_collision_and_click(part1_rect_slot_6, mouse_rect):
                selected_background=Night_WaterFall_Background_GIF
                PART=2

            if check_collision_and_click(Arrow_R_rect,mouse_rect) and cd > 80:
                back_ground_selection=2
                cd=0
            if check_collision_and_click(Arrow_L_rect,mouse_rect) and cd> 80:
                back_ground_selection=2
                cd=0   

        elif back_ground_selection==2:
            RainFall_Background_GIF_frame_mini = RainFall_Background_GIF_mini.get_current_frame()
            RainFall_Background_GIF_frame_surface_mini = image.fromstring(RainFall_Background_GIF_frame_mini.tobytes(), RainFall_Background_GIF_frame_mini.size, RainFall_Background_GIF_frame_mini.mode)
            RainFall_Background_GIF_frame_surface_mini = transform.scale(RainFall_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(RainFall_Background_GIF_frame_surface_mini, (294, 185))                        
            if check_collision_and_click(part1_rect_slot_1, mouse_rect):
                selected_background=RainFall_Background_GIF
                PART=2
            Tywan_Background_GIF_frame_mini = Tywan_Background_GIF_mini.get_current_frame()
            Tywan_Background_GIF_frame_surface_mini = image.fromstring(Tywan_Background_GIF_frame_mini.tobytes(), Tywan_Background_GIF_frame_mini.size, Tywan_Background_GIF_frame_mini.mode)
            Tywan_Background_GIF_frame_surface_mini = transform.scale(Tywan_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Tywan_Background_GIF_frame_surface_mini, (728, 185))
            if check_collision_and_click(part1_rect_slot_3, mouse_rect):
                selected_background=Tywan_Background_GIF
                PART=2
            Under_Water_City_Background_GIF_frame_mini = Under_Water_City_Background_GIF_mini.get_current_frame()
            Under_Water_City_Background_GIF_frame_surface_mini = image.fromstring(Under_Water_City_Background_GIF_frame_mini.tobytes(), Under_Water_City_Background_GIF_frame_mini.size, Under_Water_City_Background_GIF_frame_mini.mode)
            Under_Water_City_Background_GIF_frame_surface_mini = transform.scale(Under_Water_City_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Under_Water_City_Background_GIF_frame_surface_mini, (294, 340))
            if check_collision_and_click(part1_rect_slot_4, mouse_rect):
                selected_background=Under_Water_City_Background_GIF
                PART=2

            Waterfall_Background_GIF_frame_mini = Waterfall_Background_GIF_mini.get_current_frame()
            Waterfall_Background_GIF_frame_surface_mini = image.fromstring(Waterfall_Background_GIF_frame_mini.tobytes(), Waterfall_Background_GIF_frame_mini.size, Waterfall_Background_GIF_frame_mini.mode)
            Waterfall_Background_GIF_frame_surface_mini = transform.scale(Waterfall_Background_GIF_frame_surface_mini, size_sel_p1)
            screen.blit(Waterfall_Background_GIF_frame_surface_mini, (728, 340))
            if check_collision_and_click(part1_rect_slot_6, mouse_rect):
                selected_background=Waterfall_Background_GIF
                PART=2
            if check_collision_and_click(Arrow_R_rect,mouse_rect) and cd > 80:
                back_ground_selection=1
                cd=0            
            if check_collision_and_click(Arrow_L_rect,mouse_rect) and cd > 80:
                back_ground_selection=1
                cd=0

    if PART==2:                
        screen.blit(GUI_CharacterSelection, (Background_x, Background_y))
        screen.blit(Arrow_L, (100,275))
        screen.blit(Arrow_R, (1000,275))
        if check_collision_and_click(Arrow_R_rect,mouse_rect) and cd > 50:

            if character_selection_character <11:
                character_selection_character=character_selection_character+1
            if character_selection_character ==11:
                character_selection_character=1

            if character_selection_character==1:
                selection_character = "BigWarrior"
            if character_selection_character==2:
                selection_character = "BloodMagicMage"
            if character_selection_character==3:
                selection_character ="EvilWizard"
            if character_selection_character==4:
                selection_character ="GiantGhost"
            if character_selection_character==5:
                selection_character ="LightningWarrior"
            if character_selection_character==6:
                selection_character ="Ninja"
            if character_selection_character==7:
                selection_character ="PistolHero"
            if character_selection_character==8:
                selection_character ="PlagueWarrior"
            if character_selection_character==9:
                selection_character ="SkullMans"
            if character_selection_character==10:
                selection_character ="ZombieWarrior"
            cd=0                    
            selection_character_path =              "VideoGameCharacters/"+selection_character+"/R/Stand.gif"
            selection_character_GIF =               GIFBackground(selection_character_path, character_selection_character_size, frame_delay=5)  
            

        if check_collision_and_click(Arrow_L_rect,mouse_rect) and cd > 50:
            
            if character_selection_character <11:
                character_selection_character=character_selection_character-1
            if character_selection_character ==0:
                character_selection_character=10

            if character_selection_character==1:
                selection_character = "BigWarrior"
            if character_selection_character==2:
                selection_character = "BloodMagicMage"
            if character_selection_character==3:
                selection_character ="EvilWizard"
            if character_selection_character==4:
                selection_character ="GiantGhost"
            if character_selection_character==5:
                selection_character ="LightningWarrior"
            if character_selection_character==6:
                selection_character ="Ninja"
            if character_selection_character==7:
                selection_character ="PistolHero"
            if character_selection_character==8:
                selection_character ="PlagueWarrior"
            if character_selection_character==9:
                selection_character ="SkullMans"
            if character_selection_character==10:
                selection_character ="ZombieWarrior"
            cd=0                    
            selection_character_path =              "VideoGameCharacters/"+selection_character+"/R/Stand.gif"
            
            selection_character_GIF =               GIFBackground(selection_character_path, character_selection_character_size, frame_delay=5)  
            

        if cd < 51:
            cd = cd + 1
        

        selection_character_GIF_frame =         selection_character_GIF.get_current_frame()
        selection_character_GIF_frame_surface = image.fromstring(selection_character_GIF_frame.tobytes(), selection_character_GIF_frame.size, selection_character_GIF_frame.mode)
        selection_character_GIF_frame_surface = transform.scale(selection_character_GIF_frame_surface, character_selection_character_size)
        screen.blit(selection_character_GIF_frame_surface, (500, 300))
    
   
    display.update()
    clock.tick(FPS)
    
    
    I get the issue at about the end in the part above
     if cd<51:
              cd=cd+1
              
      I would really appreciate help on this thank you

**Comment by FirefoxMetzger** [comment] 2023-07-18 11:25
@CaptainNichols Hard to say why it doesn't work without access to the images involved. Also, your code snippet is quite long and not well-formatted, which makes it hard for me to do a static analysis.

Could you create a smaller (less code) example that reproduces the problem so that I can more easily look at what is going wrong?

**Comment by FirefoxMetzger** [comment] 2023-08-08 14:04
Did you manage to resolve the issue @CaptainNichols ? If not, please let me know and ideally provide a short code example.

If you did solve it, I suggest we close the issue to keep this issue tracker clean. Also, if I don't hear anything in the next couple of days, I will close the issue too. Feel free to write here and I can reopen if the problem is not solved.

**Comment by CaptainNichols** [comment] 2023-08-25 19:53
Am sorry I didn't read this , thought i wouldn't get a reply , no it
didn't get resolved but i found a solution , cutting the gif into frames
and loading each frame separately , anyways thank you for your concern.
Have a nice day.

**Closed** 2023-08-26 12:14 UTC
Labels: type: question/support, plugin: pillow
