### ISSUE TITLE
tifffile plugin writes unexpected multi-page files from 3d arrays

### ISSUE THREAD

**Issue by slanzmich** [imageio/imageio#849] opened 2022-07-26 05:29 UTC
Writing a TIFF image from an array of shape (256, 256, 3) writes a multipage TIFF with 256 pages. (This uses the legacy `tifffile` plugin.)

To write an RGB image of shape (H, W, 3), one needs to call `imageio.v3.imwrite` with an image of shape (1, H, W, 3), which I would expect to confuse some users. Writing an image of shape (3, H, W) creates a TIFF with three pages, which is again different.

One could handle some special cases separately, similar to what is done in in the `pillow` plugin:

```python
if ndimage.ndim == 3 and ndimage.shape[-1] in [1, 3, 4]: ...
```

I tried writing a few images of the highly ambiguous shape (20, 20, 20, N). For `N not in [1, 3, 4]`, opening the file in imageJ creates a stack of 400 images. A trailing dimension of size 1, 3, or 4 produces a stack of 20 images. Having the same behavior for a 3d array (i.e. write a single image for these three cases) would be consistent.

**Comment by FirefoxMetzger** [comment] 2022-07-26 08:16
> Writing a TIFF image from an array of shape (256, 256, 3) writes a multipage TIFF with 256 pages.

This sounds like a bug, because it should become a single RGB page. I will see if I can write a unit-test for this that reproduces the problem and then I will have a look at why this happens :)

> Writing an image of shape (3, H, W) creates a TIFF with three pages, which is again different.

This is intended. Vanilla TIFF can't store channel-first images on a single page. As such we have to either split the image into multiple pages or swap the axis to make the image channel last. 

We chose the road of splitting into pages and, if memory serves, we did so for two reasons: (1) It is shape-preserving for the round-drip of `iio.imread(iio.imwrite("<bytes>", data), index=...)` and (2) because TIFF usually occurs in the context of bioinformatics and here a shape of `(3, H, W)` often doesn't mean that the first axis represents the RGB colorspace. Instead, these are often different colors of staining pictures and they may occur in numbers other than 3 and may be colors other than RGB, so it's better to be conservative.

> I tried writing a few images of the highly ambiguous shape (20, 20, 20, N). For N not in [1, 3, 4], opening the file in imageJ creates a stack of 400 images.

Yes, because ImageJ uses its own TIFF variant to retain shape information which, I believe, they call ImageJ Hyperstacks. Very loosely speaking they save slices of the image on individual pages and then store some metadata in the comments of the TIFF which is then used to later reconstruct the shape. If you just `iio.imwrite("my.tiff", ...)` this metadata is missing (we write tifffile TIFFs by default, not hyperstacks) and ImageJ will simply load and stack all the pages in the file.

I'm actually not sure if we can write hyperstacks (never tried), but if `tifffile` can do this then we should be able to do it to :)

> A trailing dimension of size 1, 3, or 4 produces a stack of 20 images

I'm not sure about `1`, perhaps it is squeezed by the legacy ImageIO plugin and interpreted as a gray image? trailing dimensions of `3` are seen as RGB and `4` is RGBA, so the result is a `(stack, height, width, channel)` array, which should be stored on `stack` many pages and when ImageJ loads and stacks pages you get the same result back.

**Comment by FirefoxMetzger** [comment] 2022-07-26 08:19
Oh, and also welcome to the joys of working with TIFF files 😅.

**Comment by FirefoxMetzger** [comment] 2022-07-26 11:51
This will be fixed in https://github.com/imageio/imageio/pull/851 .

Turns out that we already had a PR in flight that had a refactor solving this issue (https://github.com/imageio/imageio/pull/816) but that one has been waiting for a while now without review, so this turns out to be a fairly quick fix :)

**Closed** 2022-07-30 05:20 UTC
Labels: type: bug, plugin: tifffile
