### ISSUE TITLE
imageio.imread wrong RGB values

### ISSUE THREAD

**Issue by jeffbaena** [imageio/imageio#414] opened 2018-12-03 16:20 UTC
Hi all,
 I am doing image processing and I have an issue with imageio. It seems that imageio does not provide the correct RGB values. I am calculating the PSNR among two images.

With matlab I get the correct values, while in python the results are different.

After quite some debugging I realized that the matrix produced by imageio is different from the one in matlab.

By double checking using opencv (cv2.imread) I came to the conclusion that it is an imageio issue.

I have also tried with PIL and PIL gives me the same (wrong) values as imageio.

Did anyone encountered this problem before?

I can provide images and scripts to whom would be interest in helping.

I am pretty sure this is an imageio/PIL bug.

Thanks in advance,

Stefano

**Comment by almarklein** [comment] 2018-12-07 08:43
Hi, what version of imagio is this with? This looks similar to #374, which is fixed in the last release.

**Comment by jeffbaena** [comment] 2018-12-07 08:56
Hi! I am using imageio 2.4.1 (seems the last version) on python 2.7.
When comparing with other methods i notice that also PIL gave the same uncorrect values.

After couple of days I've noticed that the problem doesn't always show up, making debugging a bit difficult. While it always shows up on PIL.

As you pointed out, it might be the alpha channel...I will have a look on that

Thanks,
Stefano

**Comment by hmaarrfk** [comment] 2019-07-16 03:09
Were you by any chance loading JPEG images? JPEG image loaders are allowed to take different shortcuts, that can create different errors even in decompression.

**Comment by jeffbaena** [comment] 2019-07-16 08:49
Dear @hmaarrfk, I was loading png images. they were taken from the Sintel dataset http://sintel.is.tue.mpg.de/ . I think this might be a bug because after an online research I have noticed other people had the same problem. I have solved using other libraries

Thanks for your help,
Stefano

**Comment by hmaarrfk** [comment] 2019-07-17 02:31
Out of curiosity, is the bug in how the dataset was saved or in PIL?

**Comment by jeffbaena** [comment] 2019-07-17 11:52
I am now using opencv and I did not encounter this problem. I stronlgy believe it is an imageio bug, and probably a PIL bug. Unfortunately some time has passed so I forgot the details :(

**Comment by hmaarrfk** [comment] 2019-07-17 12:38
got it! thanks

**Comment by cgohlke** [comment] 2019-12-03 08:53
This is issue is likely due to `cv2.imread` returning colors in `BGR` instead of `RGB` order.

**Comment by jeffbaena** [comment] 2019-12-03 15:02
@cgohlke  I think not, since I was not using opencv, I was using imageio at the time

**Comment by cgohlke** [comment] 2019-12-03 16:16
OK, thanks for confirming. I scanned some thousands of the PNG's in MPI-Sintel and could not reproduce the issue (`imagio.imread() != cv2.imread()[..., ::-1]`).

**Comment by FirefoxMetzger** [comment] 2021-06-30 05:48
Since we can't seem to reproduce this, I will close the issue for now. If somebody encounters this again please feel free to open a new issue. If you can add a snippet of code that demonstrates what is going wrong, even better :)

**Closed by FirefoxMetzger** 2021-06-30 05:48 UTC
Labels: plugin: pillow, type: question
