### ISSUE TITLE
Cannot store certain PNG with transparency

### ISSUE THREAD

**Issue by pohlt** [imageio/imageio#575] opened 2020-12-02 20:38 UTC
I recently loaded a PNG from Google and tried to save it using this code:
```python
import imageio
img = imageio.imread("https://www.google.com/logos/doodles/2020/december-holidays-day-1-6753651837108829.5-s.png")
imageio.imsave("img/test.png", img)
```
The `imsave` gives me an `OSError: cannot use transparency for this mode`.

After some investigation, I found out that `img._meta` contains a `transparency` key. If I delete it using `img._meta.clear()` I can save the image.

I'm attaching the PNG for reference: ![december-holidays-day-1-6753651837108829 5-s](https://user-images.githubusercontent.com/5302291/100928380-6a91e200-34e6-11eb-914b-02333bf037c0.png)

Stay safe,
Tom

The package versions are:
```
imageio    2.9.0
numpy      1.19.4
Pillow     8.0.1
```

**Comment by almarklein** [comment] 2020-12-03 21:47
Thanks for the report Tom! Another case to take into account for the metadata stuff ...

**Comment by FirefoxMetzger** [comment] 2021-11-07 15:25
Unfortunately, I can't reproduce this. If I run the snippet above the image gets downloaded and stored without any error and the result is transparent as desired.

@pohlt Could you try upgrading to the latest version of ImageIO and running this locally to see if it has been fixed? If it is, or if this is no longer an issue for you, I will go ahead and close this. Otherwise, please let me know so that we can figure out what is different between our two versions.

*Note: I will also close this issue as stale if I don't hear anything in the next couple of days. If it is still an issue, please feel free to comment and I can reopen.*

**Comment by pohlt** [comment] 2021-11-07 15:47
I already forgot about this issue. Thanks for following up.

Ok, so I tried the same operations as described above and I see exactly the same behavior (and the fix still works).

Here's the full traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tom/temp/without_ssp/lib64/python3.9/site-packages/imageio/core/functions.py", line 195, in imwrite
    return file.write(im, **kwargs)
  File "/home/tom/temp/without_ssp/lib64/python3.9/site-packages/imageio/core/imopen.py", line 303, in write
    writer.append_data(image)
  File "/home/tom/temp/without_ssp/lib64/python3.9/site-packages/imageio/core/format.py", line 492, in append_data
    return self._append_data(im, total_meta)
  File "/home/tom/temp/without_ssp/lib64/python3.9/site-packages/imageio/plugins/pillow_legacy.py", line 457, in _append_data
    PillowFormat.Writer._append_data(self, im, meta)
  File "/home/tom/temp/without_ssp/lib64/python3.9/site-packages/imageio/plugins/pillow_legacy.py", line 379, in _append_data
    img.save(self._fp, format=self.format.plugin_id, **self._meta)
  File "/home/tom/temp/without_ssp/lib64/python3.9/site-packages/PIL/Image.py", line 2240, in save
    save_handler(self, fp, filename)
  File "/home/tom/temp/without_ssp/lib64/python3.9/site-packages/PIL/PngImagePlugin.py", line 1312, in _save
    raise OSError("cannot use transparency for this mode")
OSError: cannot use transparency for this mode
```

My test setup:

```
Python 3.9.7 (default, Aug 31 2021, 01:14:27) [GCC] on linux

Package    Version
---------- -------
imageio    2.10.3
numpy      1.21.4
Pillow     8.4.0
pip        21.3.1
setuptools 57.4.0
```

> Unfortunately, I can't reproduce this. If I run the snippet above the image gets downloaded and stored without any error and the result is transparent as desired.

When I delete the `transparency` key in `img._meta` I can store the image _and_ the image contains the correct transparency. When you (down)load the image, do you get the `transparency` key in `img._meta`?

**Comment by FirefoxMetzger** [comment] 2021-11-07 16:29
@pohlt Thanks for the fast response. I see what happened now. I was on a feature branch (#680 ) and the refactor there seems to fix this. My mistake for not noticing this.

Running from master, I can indeed reproduce the exception:

```python
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imageio
>>> img = imageio.imread("https://www.google.com/logos/doodles/2020/december-holidays-day-1-6753651837108829.5-s.png")
>>> imageio.imsave("test.png", img)     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\functions.py", line 195, in imwrite
    return file.write(im, **kwargs)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\imopen.py", line 303, in write
    writer.append_data(image)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\format.py", line 492, in append_data
    return self._append_data(im, total_meta)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\plugins\pillow_legacy.py", line 457, in _append_data
    PillowFormat.Writer._append_data(self, im, meta)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\plugins\pillow_legacy.py", line 379, in _append_data
    img.save(self._fp, format=self.format.plugin_id, **self._meta)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2240, in save
    save_handler(self, fp, filename)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\PngImagePlugin.py", line 1312, in _save
    raise OSError("cannot use transparency for this mode")
OSError: cannot use transparency for this mode
```

Considering that the PR branch does the right thing, the new (v3) pillow plugin should fix this. Indeed, I can get the desired image if I run 

```python
>>> imageio.v3.imwrite("test2.png", img, mode="RGBA")
```

@pohlt What does the above line do for you?

**Comment by pohlt** [comment] 2021-11-07 17:05
@FirefoxMetzger Works for me. 👍🏼 

OT: I'm surprised that `imageio.v3.imwrite("test2.png", img)` stores a broken image, but maybe that's expected.

**Comment by FirefoxMetzger** [comment] 2021-11-07 18:56
@pohlt Awesome, then we have a fix. I will have a think if this can easily be integrated into the current v2 API, or if it will simply fix itself as we transition into v3.

> OT: I'm surprised that `imageio.v3.imwrite("test2.png", img)` stores a broken image, but maybe that's expected.

Yes this is expected since that call violates assumptions. V3 switches the default writing mode to `RGB`, because it's more popular than `RGBA`. The corruption happens when we call `PIL.Image.fromarray(img, mode=...)` with `mode="RGB"` (default) under the hood. The technical reason (if that is interesting to you) is, because `img`'s data buffer will be interpreted as a c-contiguous `(44, 120, 3)` while actually being c-contiguous and of shape `(44, 120, 4)`, which introduces an offset that renders as the artifact you see in the result image.

In v3 we have to rely on the user specifying the correct mode because v3 treats metadata and image data separately. `imwrite` thus assumes to get a plain old `ndarray` and has to look elsewhere for input metadata such as the colorspace being used.

That being said, we might be able to make a channel-last assumption (it's pretty common for IO I guess, and true for pillow) and then raise an exception if the number of channels in the data doesn't match the colorspace. Not sure if this could go wrong somewhere though...

**Comment by pohlt** [comment] 2021-11-07 20:59
Thanks for the explanation. Makes sense.

And thanks a lot for this great package! 🙏

**Comment by FirefoxMetzger** [comment] 2021-11-19 14:59
Closing this since it is fixed in v3. If anyone needs this in v2.X, please leave a comment :)

**Closed by FirefoxMetzger** 2021-11-19 14:59 UTC
Labels: type: bug, plugin: pillow
