### ISSUE TITLE
Can not imwrite a JPG with e.g. ".part" suffix

### ISSUE THREAD

**Issue by estan** [imageio/imageio#781] opened 2022-04-08 12:35 UTC
@FirefoxMetzger Hey, in 2.11.0 and later, I can not write a JPG with a ".part" suffix. This is with current master:

```
(testenv) estan@edison:~$ python3 -c 'from imageio import imwrite; imwrite("/tmp/a.jpg.part", [[[1,1,1]]], format="jpg")'
Traceback (most recent call last):
  File "/home/estan/imageio/imageio/core/imopen.py", line 188, in imopen
    return loader(request, **kwargs)
  File "/home/estan/imageio/imageio/core/imopen.py", line 177, in loader
    return config.plugin_class(request, **kwargs)
  File "/home/estan/imageio/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/home/estan/imageio/imageio/core/legacy_plugin_wrapper.py", line 74, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `JPEG-PIL` can not write to `/tmp/a.jpg.part`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/estan/imageio/imageio/v2.py", line 195, in imwrite
    with imopen(uri, "wi", plugin=format) as file:
  File "/home/estan/imageio/imageio/core/imopen.py", line 206, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `jpg` can not handle the given uri.
(testenv) estan@edison:~$
```

This used to work fine with 2.10.5 and earlier versions.

If I pass `format="jpg"` to imwrite then I expect it to not care about the output file suffix.

**Comment by FirefoxMetzger** [comment] 2022-04-08 13:49
Thanks for the report @estan . I can reproduce this on master. The reason for this behavior is that v2.11 starts to call a legacy plugin's `can_read` and `can_write` methods before reading/writing anything, which it should have been doing all along, but somehow didn't. For the legacy pillow plugin `can_write` is based on the file extension, so when you ask it to write to a `.part` file it won't recognize the extension and (conservatively) claim that it can't fulfill the request (more on this below).

You can work around this issue by writing to bytes or BytesIO and then dumping the result into a file:

```python
#ImageIO v2.16.1
import imageio.v2 as iio
from pathlib import Path

img = iio.imread("imageio:chelsea.png")
jpg_encoded = iio.imwrite("<bytes>", img, format="JPG")
Path("/tmp/a.jpg.part").write_bytes(jpg_encoded)

```

or via the v3 API and the (more accurate) `format_hint`:

```python
#ImageIO v2.16.1
import imageio.v3 as iio
from pathlib import Path

img = iio.imread("imageio:chelsea.png")
jpg_encoded = iio.imwrite("<bytes>", img, format_hint=".jpg")
Path("/tmp/a.jpg.part").write_bytes(jpg_encoded)
```

---

Now going back to conservatively declining to write files with unknown extensions there is a (potentially controversial) discussion question: Should ImageIO ignore the file extension, enforce it, or allow ignoring the file extension in certain circumstances? 

I personally think it should enforce it, because (a) it leads to obfuscation about what the file actually is vs what it claims to be. Also, (b) a lot of readers (and also Windows as an OS) rely solely on the extension to identify the file and decide what to do with it. Allowing the extension to mismatch can thus render data unusable unless you are expert enough to know how to re-identify files based on their header. Finally, (c) it resolves situations like `iio.imwrite("my.jpg", format_hint=".png")`; is the `.jpg` the typo or the `.png`? Its likely better to raise and let the user decide.

That said, I am open to alternative views and curious to see what you (@estan ) think about this. Actually, I'd also like to know how @almarklein and @jni think about this (if either of you would like to comment).

**Comment by almarklein** [comment] 2022-04-08 15:53
In any case I think that `io.imwrite("my.part", format_hint=".jpg")` should just work, and not complain about the `.part` extension. I would even say that if a user provides the format_hint, imageio should assume the user knows what he's doing, and `iio.imwrite("my.jpg", format_hint=".png")` should just write a png.

**Comment by estan** [comment] 2022-04-08 17:30
I agree with @almarklein. 

> [...] or allow ignoring the file extension in certain circumstances?

I think it should ignore the suffix if the output format is explicitly specified. There are valid reasons for using another prefix.

In our case, we write to a `.jpg.part` name first, and then atomically rename the file into it's final name once the write has successfully finished, because within the framework we are using it's important that files are written atomically. We could of course use another name for the temp file that *do* end in `.jpg`, but this would not fit within our framework.

I think this is common practice, think of e.g. browsers that download files with a nonsense suffix and then rename, precisely because they don't want the files to appear as complete in the file system until they are.

**Comment by FirefoxMetzger** [comment] 2022-04-10 06:11
> In any case I think that io.imwrite("my.part", format_hint=".jpg") should just work, and not complain about the .part extension.

The reason why we chose `format_hint` as a name - instead of something like `format`, or `format_overwride` - is because it really is just a hint for the plugin/backend selection logic to find a fast-path in case the extension is missing (https://github.com/imageio/imageio/pull/734#discussion_r794660085), at least in the case of reading data. I think it would be confusing if a `..._hint` suddenly becomes more than a hint.

That said, I also just realized that - in the case of writing - `format_hint` does become authoritative, since there is no file header or anything that is "more true" than the actual extension or the hinted extension. Here, the actual extension currently has a higher priority than the hint. We could change that around, and this would solve/close this issue, but I am again hesitant about a `..._hint` having priority over an actual thing.

I wonder if there is a solution that gets us the best of both worlds. We could add a `overwrite_extension` kwarg, which would be clear. I wonder though if that is our best option or if we would be starting to proliferate/muddle up our API.

**Comment by estan** [comment] 2022-04-10 07:20
The parameter name is `format` (https://imageio.readthedocs.io/en/v2.16.1/_autosummary/imageio.imwrite.html#imageio.imwrite). I see you've changed this to `format_hint` in the v3 API but `__init__.py` imports `imwrite` from `v2.py`.

I think in the case of writing `format` should be authoritative, and I think it should have that name for writing functions. I don't think a library should care what the application author calls their files in the case of writing, not if the application author explicitly says what format they want.

**Comment by FirefoxMetzger** [comment] 2022-04-11 07:04
Hm, what do you guys think of deprecating `format_hint` and replacing it with `format` that would always be authoritative? So if you specify `format=".jpg"` when writing, it will write a jpg to the resource regardless of extension. Similarly when you specify `format=".jpg"` when reading it will try to read the resource as jpg regardless of file header or extension. Would that be intuitive?

**Comment by almarklein** [comment] 2022-04-11 08:34
> Hm, what do you guys think of deprecating format_hint and replacing it with format that would always be authoritative? 

Plus one for me!

Some thoughts: we might also consider a different approach for reading and writing. When writing a file, the user *defines* what to write. This is the extension by default, but indeed specifying a format should use that given format, i.e. by authoritative.

For reading, it's different, because the file is already in a specific format. We have mechanics in place to try and auto-detect the format, but need a way for the user to specify the format when it fails. A (non-athorative) hint seems nice, but what if it's ignored (imageio keeps using the extension) and it still fails? There is more room for discussion here, but I think it should be authoritative for reading as well ...

**Comment by FirefoxMetzger** [comment] 2022-04-18 16:51
Okay, then let's see how we can introduce `format`. From my side, there are a few open points:

- How should we deal with backends that don't allow us to explicitly control the format, e.g., freeimage, pyav, imageio-ffmpeg,  openCV, etc.? Should they ignore `format`, emit a warning that format might be ignored, or raise an exception and refuse to read the file because they might read it in an undesired format.
- Should this behavior be different for backends that only support a single format (e.g. tifffile) deal with format? I.e., is a scenario like `iio.imread(something, plugin="tifffile", format=".png")` any from the above?
- How can users specify formats that don't have an explicit extension associated with them?

**Comment by estan** [comment] 2022-04-20 06:53
I was thinking just of the write function (imwrite), so have not considered reading. Are there backends where the output format cannot be set explicitly?

In our case we have no need to specify format explicitly when reading, as the files will have .jpg format when they are read (that is also done with another library typically).

Does the API really need to be symmetric in this regard? Could not explicit format be added only to writing functions?

**Comment by almarklein** [comment] 2022-04-20 08:26
> How can users specify formats that don't have an explicit extension associated with them?

I suppose a format can be specified both by name and by extension.

> How should we deal with backends that don't allow us to explicitly control the format

Good point. I think this should be dealt with on the plugin level. 

> Should this behavior be different for backends that only support a single format (e.g. tifffile) deal with format?

In that case the setting of `format` is more likely just to select an appropriate plugin. Trying to set `.png`  on the fiffile plugin should raise an error.

> Does the API really need to be symmetric in this regard? Could not explicit format be added only to writing functions?

I think it does not necessarily have to be symmetric. I think I'd still call it just `format` in both cases, but document that for reading the plugin may only use it as a hint. Maybe this would help some of the edge-cases @FirefoxMetzger?

**Comment by estan** [comment] 2022-04-20 16:28
Alright. For our part we're just interested in the writing part - we want to be able to explicitly state the output format, regardless of the output file name. I.e. get the behavior we had before 2.11.0 back.

Also, more philosophically, the file is not a valid JPG from the API user's POV until imwrite has successfully returned, so it makes sense to write it to a foo.jpg.part which is then atomically moved to foot.jpg, to not leave seemingly intact JPGs in the event of e.g. a powerloss.

**Comment by FirefoxMetzger** [comment] 2022-04-21 04:43
I gave this some thought yesterday evening.

On the reading side, I must admit that I kind of like the way it is now. I like that the file header is authoritative and I like that the available kwargs convey that explicitly, i.e., I like that we chose `format_hint` instead of `format`. We could debate if the extension should have higher priority than `format_hint` (how it is now), or vice versa, but since the current issue is on writing, I'd vote for keeping this as is.

As for writing, I agree that we should be able to state the output format regardless of the file extension. Currently, the extension has priority over `format_hint`. We could flip that around and solve the problem that way, but it seems weird that `format_hint` (with a `_hint` in the name)  dictates the output format when an extension is present, which started the current discussion on changing to `format`, how to do it, and what the implications of this would be.

As an alternative to renaming and potentially going through a deprecation cycle, what do you two think about introducing a new kwarg called `ignore_extension`? It would be available when writing and, if `ignore_extension=False` (default) we would check the extension to determine the output format (if present) and if `ignore_extension=True` we skip it and go straight to `format_hint` (and whatever else might help determine the correct backend and extension to use). This should solve the current problem, and writing JPG to a `.part` file would then take the form

```python
iio.imwrite("some.jpg.part", format_hint=".jpg", ignore_extension=True)
```

**Comment by almarklein** [comment] 2022-04-21 07:28
The way I see it, the extension is itself a hint for the format, and specifying a format should always override that. Both for reading and writing.

For reading, a plugin can still examine the contents of the file and find the actual format that way. And if deviates from either the extension or the given format (or format hint), than it should indeed just use that. So the "line of command" would IMO be: file header, format if given, extension.

**Comment by FirefoxMetzger** [comment] 2022-04-22 06:04
@almarklein In this case, how about calling it `extension` as in

```python
"""
extension : str
    Treat the provided ImageResource as if it had the given extension. This
    affects the order in which backends are considered, and when
    writing this may also influence the format used when encoding.
"""
```

My main concern about `format` is that the name is easily misunderstood as dictating the format. This would only be true when writing with backends that support more than one format (so far they all decide the encoder to use based on the extension), but would be false for backends that support only one format (they simply write that format regardless of extension). It would also be false when reading anything (backends check the file header and ignore the extension). A name like `extension` or `ignore_extension=False` would be more explicit and avoid this false perception.

**Comment by FirefoxMetzger** [comment] 2022-04-29 14:28
@almarklein I'm still curious about your thoughts on this. The technical fix for this is rather small, so we could implement it quite fast once we reach a consensus on the correct name to use. You've heard my worries about the potential confusion of calling it `format`, but - in the spirit of building momentum - if you still prefer the name `format` we can also go ahead with that and I can write a PR during the coming week.

**Comment by almarklein** [comment] 2022-04-29 15:42
I like the `extension` solution! Simple and explicit!

**Closed** 2022-05-06 08:39 UTC
Labels: type: bug, core
