### ISSUE TITLE
Volume formats: HDF5, N5, Zarr

### ISSUE THREAD

**Issue by clbarnes** [imageio/imageio#469] opened 2019-08-14 15:16 UTC
Through optional dependencies.

- hdf5 through h5py rather than PIL
- [N5](https://github.com/saalfeldlab/n5/) through [z5py](https://github.com/constantinpape/z5) (depends on conda) or [pyn5](https://github.com/pattonw/rust-pyn5) 
- [Zarr](https://github.com/zarr-developers/zarr-python) through z5py or the reference zarr-python

pyn5 and z5py are both designed to have an interface compatible with h5py, so a single base class could potentially cover all of these formats with very minor variations (specifically, I was inspired by z5py to write ABCs in [h5py_like](https://github.com/clbarnes/h5py_like), which is used by pyn5). For now, they can be eagerly loaded, although their real strength is in lazy loading large datasets.

Zarr has been picked up by netCDF, xarray, and dask already.

**Comment by FirefoxMetzger** [comment] 2021-06-24 20:42
@clbarnes Is this a duplicate of #645 and #646 ?

**Comment by clbarnes** [comment] 2021-06-24 22:30
Yes, a pre-duplicate! Separate issues is probably better, even if they all get done at the same time (when I eventually get round to it).

**Comment by FirefoxMetzger** [comment] 2021-06-25 03:34
@clbarnes I agree. I will close this issue here in favor of the others :)

**Closed by FirefoxMetzger** 2021-06-25 03:34 UTC
Labels: plugin: new
