### ISSUE TITLE
ffmpeg plugin computes nframes incorrectly

### ISSUE THREAD

**Issue by headdab** [imageio/imageio#392] opened 2018-10-11 19:50 UTC
The following code is not right.   In my specific case, I have a video that has 5464 frames for which this computation returns 5474.  This results in the most basic code, i.e. a simple loop over reader frames to fail.

```
           # Estimate nframes
            self._meta["nframes"] = np.inf
            if self._meta["fps"] > 0 and "duration" in self._meta:
                n = int(round(self._meta["duration"] * self._meta["fps"]))
                self._meta["nframes"] = n
```

I think I understand how you are computing this, from the first few lines printed out when ffmpeg starts up, but you should get these parameters from the metadata stored in the file using ffprobe.  For example, run

    `ffprobe -hide_banner -loglevel error -of flat -show_streams VIDEO.mp4`

and look for 'nb_frames'.  I'm not sure if you need fps for imageio, but the relationship between the number of frames, fps, and duration is sometimes not exact.  I've found that using nb_frames to be the most reliable measure.

**Comment by almarklein** [comment] 2018-10-12 07:00
Yes, we are aware of this. The plan is to write a new plugin based on PyAv (#115)

**Comment by almarklein** [comment] 2018-11-06 14:42
Sort of a duplicate of #304. Forget that earlier comment about PyAv, apparently that is only installable via conda.

**Comment by almarklein** [comment] 2019-02-05 23:38
Closing this per #425. The ffmpeg plugin now simply makes no assumptions about the number of frames, since calculting them is either inexact (as you rightly pointed out) or expensive. I've also looked at using ffprobe, but it would add such considerable overhead that we cannot do it for each read request. Instead one can use `reader.count_frames()` in case one wants to know the exact number of frames.

**Closed by almarklein** 2019-02-05 23:38 UTC
