### ISSUE TITLE
No seeking allowed!

### ISSUE THREAD

**Issue by insatmc** [imageio/imageio#238] opened 2017-03-07 11:02 UTC
I am using imageio inside a AWS Lambda function.

When reading a file with imageio.imread I got an Error : No seeking allowed!

What's the meaning of this error ?

**Comment by almarklein** [comment] 2017-03-07 11:15
Looks like a duplicate of #202, though a fix for that made it into the last release. Are you using the latest version?

**Comment by insatmc** [comment] 2017-03-07 11:19
I don't think that's the same error as I have:

this is the complete trace of the error


No seeking allowed!: RuntimeError
Traceback (most recent call last):
File "/var/task/func.py", line 32, in handler
images.append(imageio.imread("https://s3.eu-west-2.amazonaws.com/run-records/"+filename))
File "/var/task/imageio/core/functions.py", line 185, in imread
reader = read(uri, format, 'i', **kwargs)
File "/var/task/imageio/core/functions.py", line 111, in get_reader
return format.get_reader(request)
File "/var/task/imageio/core/format.py", line 169, in get_reader
return self.Reader(self, request)
File "/var/task/imageio/core/format.py", line 218, in __init__
self._open(**self.request.kwargs.copy())
File "/var/task/imageio/plugins/pillow.py", line 299, in _open
return PillowFormat.Reader._open(self)
File "/var/task/imageio/plugins/pillow.py", line 85, in _open
pil_try_read(self._im)
File "/var/task/imageio/plugins/pillow.py", line 375, in pil_try_read
im.getdata()[0]
File "/var/task/PIL/Image.py", line 1153, in getdata
self.load()
File "/var/task/PIL/ImageFile.py", line 195, in load
seek(offset)
File "/var/task/imageio/core/request.py", line 481, in seek
ori_seek(i, mode)
File "/var/task/imageio/core/request.py", line 484, in fail_seek
raise RuntimeError('No seeking allowed!')
RuntimeError: No seeking allowed!

**Comment by almarklein** [comment] 2017-03-08 09:17
Do you have a minimal example to reproduce this? I tried the code below, and it works fine:
```py
im = imageio.imread('https://github.com/imageio/imageio-binaries/raw/master/images/camera.png')
```

What version of Pillow are you using (I tried on 4.0.0)?

**Comment by almarklein** [comment] 2017-05-21 01:31
ping @insatmc. I'd like to do a release soon. Would be nice to fix this this is still a problem.

**Comment by almarklein** [comment] 2017-05-25 13:24
I'm about to do a release. As a workaround you can download the image first, and then provide the raw bytes to imageio:

```py
import imageio
from urllib.request import urlopen

url = 'https://github.com/imageio/imageio-binaries/raw/master/images/camera.png'
data = urlopen(url).read()
im = imageio.imread(data, 'png')
```

**Comment by thibaultleouay** [comment] 2018-01-02 17:03
I can reproduce this issue with this snippet 

`
import imageio

im = imageio.imread("https://github.com/imageio/imageio-binaries/raw/master/images/camera.png")
print(im.shape)


im = imageio.imread("https://github.com/imageio/imageio-binaries/raw/master/images/rommel.jpg")
print(im.shape)
`

**Comment by almarklein** [comment] 2018-01-03 09:53
Aha! It works for png, but the Pillow JPG reader uses seek, which is not supported. 

Note that imageio already provides measures to make Pillow work (it overloads the seek operation so that when Pillow uses seek for the current position, it's a no-op). But this is not enough for the JPEG reader. There is not much we can do about this, except perhaps pre-loading the entire image, but thats the same as the workarount posted above. You could try bring this issue up at the Pillow project though.

**Comment by almarklein** [comment] 2018-02-21 00:03
Fixed

**Comment by almarklein** [comment] 2018-03-12 21:26
(this failed to auto-close when #311 was merged because of a typo)

**Closed by almarklein** 2018-03-12 21:26 UTC
Labels: plugin: pillow, type: bug

**Comment by arudmin** [comment] 2018-03-15 02:45
Same problem for me. 
Test img http://telegra.ph/file/85f169c05ccaabd6bce48.jpg

**Comment by almarklein** [comment] 2018-03-15 07:58
Should be fixed in the next release.

**Comment by almarklein** [comment] 2018-03-19 13:21
(just tried, and it works with the latest master)
