### ISSUE TITLE
issue saving exr file

### ISSUE THREAD

**Issue by moushkka** [imageio/imageio#144] opened 2016-04-02 10:14 UTC
Saving to exr seems to result in a black image on my computer.

``` python
import numpy as np
import imageio
original = imageio.imread('original.exr')
print('original min: {} max: {}'.format(np.min(original), np.max(original)))
imageio.imsave('saved.exr', original)
saved = imageio.imread('saved.exr')
print('saved min: {} max: {}'.format(np.min(saved), np.max(saved)))
```

results in the printout:

```
original min: 0.62353515625 max: 1.0
saved min: 0.0 max: 0.0
```

Here is an exr file for testing.
[original.exr.zip](https://github.com/imageio/imageio/files/200776/original.exr.zip)

I'm using python 3.5.1.
imageio is version 1.5 installed using pip.
I'm running this on osx.

**Comment by almarklein** [comment] 2016-04-11 13:05
Reproduced on Windows. It could be a bug either in FreeImage, or in our freeimage wrapper. It does not help to write as uint8 (because exr does not support that).

**Comment by so-rose** [comment] 2016-09-08 18:49
Same exact issue here. Trying to write '.hdr' images also breaks. Python 3.5.1/imageio 1.5 via pip on Debian Linux.

I **really** would like to use imageio to drive my entire current project's IO (https://github.com/so-rose/openlut). EXR is a must, though, alas this bug is very irritating! (I might implement imageio anyway as the default plugin for formats other than EXR and DPX, for now).
<br>
I would love to fix this myself & make a pull request, if I knew where to start. I have no experience with ctypes, and limited experience with C++, however. If you point me in the right direction, I can try, though!

**Comment by almarklein** [comment] 2016-09-08 22:24
@so-rose I good first test would be to try and see if the same error occurs with freeimage itself. That way we could establish whether its a problem with FreeImage or our wrapper.

Although, if this problem occurs with *every* exr image, it is very likely the wrapper.

**Comment by so-rose** [comment] 2016-09-09 02:29
Hmm... FreeImage, C++ version, works great (I also do think that EXR and HDR not working would have been noticed!).

I've also tried out loading some different images - 16-bit, 8-bit, hdr depth channel, etc. . So far, nothing - just a black file, even though the array looks fine

A note about the black EXR/.hdr output: It seems to be 16 bit black values, not 32 bit, which is a bit curious - imageio seems to save according to dtype quite well. I also replicated the black EXR and .hdr output in Python 2.7.12.


So, **it's most likely the wrapper**!
<br>
I'd also just like to say that imageio is **exactly** what I've been looking for for months now - a "just give me/take the raw numpy array, no color management, and I'll do the in between stuff" solution. Thank you a bunch!

**Comment by almarklein** [comment] 2016-09-11 08:45
Thanks for testing this out so we can narrow down the problem to the wrapper! If you have the time, the module where the bug should be is [_freeimage.py](https://github.com/imageio/imageio/blob/master/imageio/plugins/_freeimage.py), which is used from the more higher level [freeimage.py](https://github.com/imageio/imageio/blob/master/imageio/plugins/freeimage.py). The latter has some code for specific formats, but EXR/HDR has no special cases here. So the bug is likely in the former module. It's not the easiest code though (ctypes wrappers rarely are :)).

**Comment by almarklein** [comment] 2016-09-24 23:06
BTW: imageio will very likely soon wrap Pillow to support the "common" formats. If Pillow can read the kind of images that you're using, it might be easier to wait for that ...

**Comment by moushkka** [comment] 2016-09-25 08:04
Pillow doesn't do exr as far as I know.
That was the reason I was interested in imageio.

There doesn't seem to be a good way to read or write exr images in python at the moment unfortunately :(

**Comment by so-rose** [comment] 2016-09-25 14:55
Yeah; even worse, I'm pretty sure Pillow assumes that the world is made up of uint8 images! So, useless for hdr work. It can't do EXR, TIFF, etc. .

If you must add a new wrapper, it might be worth wrapping ImageMagick or GraphicsMagick, which really has *insane* format support (but no 32 bit though, so it's no solution for HDR image work).

**Comment by almarklein** [comment] 2017-05-25 13:56
I just wanted to look into this, but it seems to actually work now:
```
original min: 0.62353515625 max: 1.0
saved min: 0.62353515625 max: 1.0
```

@moushkka @so-rose could you confirm?

**Comment by moushkka** [comment] 2017-05-25 15:32
The issues I had were fixed by pull request #165 I think.
Seems to work now for me.

**Comment by almarklein** [comment] 2017-05-25 22:35
Oh, right! We should probably have closed this when we merged it. Doing so now. Thanks again!

**Closed by almarklein** 2017-05-25 22:35 UTC
Labels: plugin: freeimage, type: bug

**Comment by so-rose** [comment] 2017-05-30 18:32
Thanks so much! Works perfectly with 2.2.
