### ISSUE TITLE
Problems reading and writing float32 RGB TIFF

### ISSUE THREAD

**Issue by KeygenLLC** [imageio/imageio#707] opened 2021-12-11 05:38 UTC
I'm not sure if this is related to post #703 and #704 so just wanted to post to double check.

In python on macOS, I tried reading a float32 RGB TIFF from a file with imageio and also with tifffile.  Trying to write this as bytes to a variable throws an error: `OSError: An unknown error occurred while initializing plugin 'tif'.`

Example:
```python
the_img = imageio.imread(path)
the_file = io.BytesIO
imageio.imwrite(the_file, the_img, format='tif')
```
tifffile example:
```python
the_img = tifffile.imread(path)
the_file = io.BytesIO
imageio.imwrite(the_file, the_img, format='tif')
```
I've only seen this with float32 RGB TIFF. Same method with 8-bit PNGs and JPG worked fine. 

My project requires an entire pipeline using RGB float32 TIFF, so hopefully there is a workaround, or if it's related to #703 and #704, hoping that will be rolled out soon. Pillow seems to die with float32 RGB, so hopefully there is a way with imageio.

Thanks

**Comment by FirefoxMetzger** [comment] 2021-12-11 13:58
Thanks for the report @KeygenLLC .

#704 rolled out 3 days ago as imageio 2.13.3, so if you are on the latest version you will have those updates. The error message that you are seeing is also triggered by a different part of the library. In your case, a plugin was successfully identified (via `format="tif"` which resolves to `tifffile`), but the plugin fails to initialize a writer. 

The exact source of the problem should be in the stack trace. In case of an "unknown error" we report the issue by chaining exceptions to also report what the unknown error is. If you could share the full stack trace, we can see where the error comes from. What would be even better is if you can share the image that is causing problems so that we can reproduce the behavior locally.

I also tried reproducing the problem locally, but without success (or rather, without getting an exception):

```python
>>> import imageio as iio                                  
>>> import numpy as np
>>> import io
>>> test_image = np.zeros((255, 255, 3), dtype=np.float32) 
>>> foo = iio.imwrite("<bytes>", test_image, format="tif")
>>> buffer = io.BytesIO()
>>> iio.imwrite(buffer, test_image, format="tif")
```

**Comment by KeygenLLC** [comment] 2021-12-11 19:29
Thanks for the quick reply. I'm using the latest version so it must be something else.

These images are from Photoshop, so it might be how it's saving the TIFF. It was saving EXR as half float which is why I switched to using TIFF in the first place. Wouldn't be surprised if it's something wonky happening on save. I have checked with `exiftool` and they are 32-bit floating point images, uncompressed.

I can't send the project files, so I made another from an unsplash image. Zip is attached.

If you want to try and make one on your end (if you have access to Photoshop 2021): 

1. Open an RGB image in Photoshop
2. Open Hue/Saturation and make saturation `-100`
3. Convert to sRGB color space if it's not already `Edit > Convert to Profile... > Destination: sRGB IEC61966-2.1`
4. Change bit-depth to 32-bits per channel `Image > Mode > 32 Bits/Channel`
5. Save as TIFF with `File > Save As...`
6. Use the Settings attached below

You can also test with a regular color image without desaturating if you make it sRGB and 32-bit. I've tried both. They are not single channel grayscale, but 3 channel RGB that has been desaturated, because the python scripts need them that way.

If you don't have access to PS, and this zip file gets corrupted being uploaded, let me know if there is an email address I can send the files to or I can put them on my server. 

Thanks

Tiff Settings
---
![TiffOptions](https://user-images.githubusercontent.com/92394639/145688793-d8a60af2-e28d-4f8d-8fad-dc8b493c354a.png)

Test Images
--- 
[TestImages_float32_Photoshop.zip](https://github.com/imageio/imageio/files/7697625/TestImages_float32_Photoshop.zip)

**Comment by FirefoxMetzger** [comment] 2021-12-11 20:05
Thanks for the images @KeygenLLC . To me, unsplash images are just fine, as long as they allow me to reproduce the problem :D

I downloaded the images you attached and did the following test:

```python
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imageio as iio
>>> img = iio.imread("test.tif")
>>> img.shape
(425, 425, 3)
>>> img.dtype
dtype('float32')
>>> import matplotlib.pyplot as plt
>>> plt.imshow(img)
<matplotlib.image.AxesImage object at 0x000001BCBF9E57F0>
>>> plt.show()
>>> foo = iio.imwrite("<bytes>", img)
>>> foo = iio.imwrite("<bytes>", img, format="tif") 
>>> import io
>>> buffer = io.BytesIO()
>>> iio.imwrite(buffer, img, format="tif")
>>> buffer.tell()
2167788
>>> buffer.seek(0)
0
>>> img2 = iio.imread("test_color.tif")
>>> buffer2 = io.BytesIO()
>>> iio.imwrite(buffer2, img2, format="tif")
>>> buffer2.seek(0)
0
>>> from_buffer = iio.imread(buffer2, format="tif")
>>> plt.imshow(from_buffer)
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
<matplotlib.image.AxesImage object at 0x000001BCBFA97880>
>>> plt.show()
>>> 

```

The images read and write fine and look visually similar to the preview that I get in the Windows Photo Viewer. They do appear darker in matplotlib, but that is a different issue. The warning `Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).` comes from the fact that the RGB image loads with negative pixel values; this, too, seems like a different issue.

Two questions:

1. I noticed in your example that you write `io.BytesIO` instead of `io.BytesIO()`. I thought this is simply a typo in the post, so I didn't comment on it earlier; however, if I do this I indeed get `OSError: An unknown error occured while initializing plugin `tif`.`. This is, however, expected since you can't write to the class object, but should instead write to an instance of `io.BytesIO`. Could you double check how the `buffer` variable is created in your case?
2. Are you using the vendored version of `tifffile`, or are you using the latest version from pypi?

**Comment by KeygenLLC** [comment] 2021-12-11 20:15
Not sure why I didn't post this, but here is the trace. Paths are abridged for NDA.

```bash
Traceback (most recent call last):
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/core/imopen.py", line 161, in imopen
    return loader(request, **kwargs)
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/core/imopen.py", line 150, in loader
    return config.plugin_class(request, **kwargs)
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/core/legacy_plugin_wrapper.py", line 67, in __init__
    if not self._format.can_write(request):
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/core/format.py", line 195, in can_write
    return self._can_write(request)
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/plugins/tifffile.py", line 390, in _can_write
    request.get_file().seek(0)
TypeError: descriptor 'seek' requires a '_io.BytesIO' object but received a 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "key_test.py", line 196, in <module>
    viz.plot_function(img_path, factor=rfactor)
  File "/Path/to/vizualize.py", line 139, in plot_function
    path, factor=rfactor
  File "/Path/to/vizualize.py", line 216, in get_function
    original_image = self._open_image(path)
  File "/Path/to/visualize.py", line 81, in _open_image
    imageio.imwrite(the_file, the_img, format='tif')
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/core/functions.py", line 195, in imwrite
    with imopen(uri, "wi", plugin=format) as file:
  File "/opt/anaconda3/envs/MYENV/lib/python3.7/site-packages/imageio/core/imopen.py", line 179, in imopen
    raise err_type(err_msg) from err_from
OSError: An unknown error occured while initializing plugin `tif`.
```

**Comment by FirefoxMetzger** [comment] 2021-12-11 20:22
@KeygenLLC Yes, the stacktrace, too, looks like imageio tries to call methods on the `io.BytesIO` class instead of calling them on a `io.BytesIO()` object. 

What does `type(the_file)` evaluate to? (this is presumably part of your code)

**Comment by KeygenLLC** [comment] 2021-12-11 20:32
> The images read and write fine and look visually similar to the preview that I get in the Windows Photo Viewer. They do appear darker in matplotlib, but that is a different issue. The warning `Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).` comes from the fact that the RGB image loads with negative pixel values; this, too, seems like a different issue.

I ran a quick Levels on the picture. It probably dipped below black. Working with post-production and CG, we often get negative float values and values above 1, hence the 32-bit float which lets us pull those back into range in compositing. My files may or may not have values beyond 0-1. Depends on what it is.

Will that cause problems because one of the reason I'm using floating point images is for this exact reason—to be able to recover blown out highlights and below black shadow details. I'm not clipping/clamping anything.
 
> 
> Two questions:
> 
>     1. I noticed in your example that you write `io.BytesIO` instead of `io.BytesIO()`. I thought this is simply a typo in the post, so I didn't comment on it earlier; however, if I do this I indeed get `OSError: An unknown error occured while initializing plugin `tif`.`. This is, however, expected since you can't write to the class object, but should instead write to an instance of `io.BytesIO`. Could you double check how the `buffer` variable is created in your case?

Oh.... man. Yeaaaaaaaaah... lol fml

Well, I feel stupid. This isn't my first time using imageio, but damned if I didn't forget to add the parens at the end. I actually copied the code from another tool _I built_, but not that part apparently...

Sorry to waste your time, man. I was going through thousands of lines of code, and somehow I just didn't notice. 🤦🏻‍♂️ I was commenting out chunks of code back and forth and running rapid tests. I might have deleted the parentheses by accident, or deleted the line and typed it back in without them. 

I owe you a beer and a burger, and you can punch me in the neck.

If I run into any actual problems I'll let you know. I'm converting a decently complex program over to imageio from PIL because it doesn't work with my files and trying to only use imageio, cv2 and tifffile. Hopefully I make it through unscathed.

**Comment by FirefoxMetzger** [comment] 2021-12-12 08:17
> Will that cause problems because one of the reason I'm using floating point images is for this exact reason—to be able to recover blown out highlights and below black shadow details. I'm not clipping/clamping anything.

Depends on what you are doing, but probably not. ImageIO itself will (as you can see above) happily read/write those values. However, downstream image processing code might rely on the assumption that `dtype=float` means pixels are in the range `[0, 1]`, and violating that might lead to strange behavior. So yes, ImageIO will be fine, but other image processing might behave unexpectedly.

> Oh.... man. Yeaaaaaaaaah... lol fml

Sounds like that solved the problem 😄 I will close this issue to keep things clean. 

Good luck migrating your code, and do let us know if you encounter any bugs in ImageIO.

**Closed by FirefoxMetzger** 2021-12-12 08:17 UTC
Labels: plugin: tifffile

**Comment by KeygenLLC** [comment] 2021-12-12 12:27
Thanks for the info about float. I'll keep that in mind and look for artifacts in case they popup elsewhere down the line.

Again, sorry about the mixup. I try to be thorough before posting issues, but must have gone blind after too many hours of testing.
