### ISSUE TITLE
Remove meta data fields that become invalid during reading (e.g. exif orientation)

### ISSUE THREAD

**Issue by higumachan** [imageio/imageio#371] opened 2018-08-24 05:14 UTC
I meet a bug in that uploaded image notebook case.

![image](https://user-images.githubusercontent.com/1011298/44566329-ef3e1380-a7a7-11e8-91a5-10402efab2cf.png)

I think save correct orientation pixels and original exif information.

**Comment by almarklein** [comment] 2018-09-03 18:44
I can reproduce this. I think what is happening is that the original meta data is saved, but is invalid since the image has already been rotated ... this bug should be part of #362.

**Comment by almarklein** [comment] 2020-01-28 10:25
I'm going to close this because we are aware of the issue, but removing the exif flag is probably not the right solution.

**Closed by almarklein** 2020-01-28 10:25 UTC
Labels: core, type: bug
