### ISSUE TITLE
Cannot build docs due to an AttributeError

### ISSUE THREAD

**Issue by ghisvail** [imageio/imageio#185] opened 2016-12-09 16:01 UTC
`python make doc html` on current master:
```
Running Sphinx v1.4.8
making output directory...
Special preparations for imageio docs:
  Prepare Format.Reader and Format.Writer for doc generation.

Exception occurred:
  File "/home/gvaillan/workspace/debian/packages/python-imageio/docs/ext/imageio_ext.py", line 68, in prepare_reader_and_witer
    Reader.__doc__ = imageio.core.format.Format.Reader.__doc__
AttributeError: attribute '__doc__' of 'type' objects is not writable
```

**Comment by almarklein** [comment] 2016-12-09 18:19
This is a duplicate of #153; docs currently need to be build on Python 3.x. Is this something you can (easily) work around by using py3k to create the docs? Otherwise its time to try and fix this for real.

**Comment by ghisvail** [comment] 2016-12-09 18:21
No problem, I can switch to the Python 3 version of sphinx-build.

**Comment by almarklein** [comment] 2016-12-09 23:51
Fixed it anyway, though if its no trouble I recommend using Python 3 regardless, because that's what runs on readthedocs and what I can sorta guarantee works correctly.

**Closed** 2016-12-09 23:51 UTC
