### ISSUE TITLE
imageio litters /usr/local in OS X

### ISSUE THREAD

**Issue by slhck** [imageio/imageio#77] opened 2015-02-22 15:51 UTC
imageio was automatically installed on my Mac (OS X 10.10.2) as a dependency of [moviepy](https://github.com/Zulko/moviepy) via `pip install moviepy`.

Apparently, it wrote `/usr/local/README.md` and several other files, such as `/usr/local/LICENSE`, thereby overwriting [Homebrew](http://brew.sh/)'s README, causing it to fail when upgrading. It also created `/usr/local/tests` and other directories I now have to manually clean up.

Please do not litter into `/usr/local`, but choose a more sensible place. I don't know how Python packaging works exactly, but `/usr/local` does not seem to be the place where a package should reside.

If this is an issue with moviepy, please let me know so I can post it there instead. If this is caused by a configuration problem on my system, I wouldn't know which one, because I haven't done anything else other than installing latest Python via `brew install python`.

**Comment by almarklein** [comment] 2015-02-23 09:47
This should not happen. But ... I see them on my system too. WTF. Will look into it...

**Comment by almarklein** [comment] 2015-02-23 09:51
cc-ing @Zulko, though I confirmed that this indeed happens on installing via pip...

**Comment by almarklein** [comment] 2015-02-23 10:14
Ah. This is due to my attempt at shipping certain files in the dist package. The files get placed in `sys.prefix`. The recent change to use MANIFEST.in fixes this (I just confirmed this), but that change was made after release 1.1. I did not know the effect was this bad. I think we need a release asap...

**Comment by almarklein** [comment] 2015-02-23 10:14
Marking as closed since this effectively has been fixed... just need a new release ...

**Closed by almarklein** 2015-02-23 10:14 UTC

**Comment by almarklein** [comment] 2015-02-23 20:35
New release on Pypi and conda (`conda install -c pyzo imageio`)

**Comment by slhck** [comment] 2015-02-23 20:36
Cool, thanks a lot for taking care of it!
