### ISSUE TITLE
Cannot read GIF image

### ISSUE THREAD

**Issue by alexforencich** [imageio/imageio#245] opened 2017-04-11 21:52 UTC
When I attempt to read in a GIF image, I get the following exception:

    Traceback (most recent call last):
      File "./wavegif.py", line 12, in <module>
        frames.append((imageio.imread("frame0.gif"), 12))
      File "/usr/lib/python3.6/site-packages/imageio/core/functions.py", line 187, in imread
        return reader.get_data(0)
      File "/usr/lib/python3.6/site-packages/imageio/core/format.py", line 341, in get_data
        im, meta = self._get_data(index, **kwargs)
      File "/usr/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 116, in _get_data
        im = pil_get_frame(self._im, self._grayscale)
      File "/usr/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 424, in pil_get_frame
        frame = p[frame_paletted]
    IndexError: index 15 is out of bounds for axis 0 with size 12

Running python 3.6.0, pillow 4.1.0, imageio 2.1.2.

**Comment by almarklein** [comment] 2017-04-12 08:01
I updated Pillow to 4.1.0 and attempted to read a GIF image, and do not run into problems. Is this a problem that you see on more images? Is this a problem that was not there in earlier versions?

Can I perhaps get access to an image for which it fails, to reproduce the error?

**Comment by alexforencich** [comment] 2017-04-12 20:08
First time using imageio, so I don't know if this is a new issue or not.  

Here is the image in question:

![frame0](https://cloud.githubusercontent.com/assets/508807/24977204/23c0aa92-1f81-11e7-9bf3-927edbe55e90.gif)

**Comment by almarklein** [comment] 2017-04-18 12:05
This is a duplicate of #210, and has been fixed in #218, though I'm about

**Closed by almarklein** 2017-04-18 12:05 UTC
