### ISSUE TITLE
Get imageshape without reading image

### ISSUE THREAD

**Issue by constantinpape** [imageio/imageio#361] opened 2018-07-24 08:00 UTC
Is there a way in `imageio` to get the shape of an image / volume without reading it into memory?

I had a look at the documentation, but couldn't find anything that would do this, as there is 
no shape information in the metadata returned by `Reader.get_meta_data` (at least not for the tiffs I am working with).

This feature would be very useful, e.g. when working with a lot of images and verifying that shapes agree before loading them.

**Comment by almarklein** [comment] 2018-07-31 08:10
Duplicate of #263. Summary: we indeed have `Reader.get_meta_data`, but it lacks some "standard" to define keys like shape and type.

**Closed by almarklein** 2018-07-31 08:10 UTC
