### ISSUE TITLE
Impossible to write greyscale images with alpha channel.

### ISSUE THREAD

**Issue by wnoise** [imageio/imageio#576] opened 2020-12-02 20:55 UTC
This is currently enforced by [line 297 in imageio/core/functions](https://github.com/imageio/imageio/blob/4b3550ddedf99ecdfa71768d20a4a6251adcbabf/imageio/core/functions.py#L297).

I'm specifically interested in the case of PNGs.  Trying directly to talk to `Writer` objects via `get_writer(..., format='PNG-PIL')` (or `'PNG-FI'`) gets writers that similarly choke.

I don't know what freeimage actually supports, but PIL does support writing these from images of type 'LA'.

Both the freeimage and PIL plugins read images like this with no problems.

**Comment by almarklein** [comment] 2020-12-03 21:49
Interesting. Yeah, we could add `2` to that list, and (reasonably) assume that's LA. May need some additional code to handle such cases correctly though.

**Comment by FirefoxMetzger** [comment] 2021-06-22 06:25
This _should_ be fixed by the new pillow plugin, since it respects all currently supported formats including LA. That said, I can't be sure without a MWE to test the behavior.

@wnoise Do you happen to still have the code snippet that produced the error? If so, would you mind sharing it? In this case, we can turn this into a regression unit-test so that it won't become a problem again in the future :)

**Comment by FirefoxMetzger** [comment] 2021-11-19 14:54
Closing this issue due to lack of activity. Writing transparent grayscale PNGs seems to work fine with the v3 pillow plugin:

```python
>>> import numpy as np
>>> import imageio as iio
>>> test_img = np.zeros((512, 512, 2), dtype=np.uint8)
>>> test_img[..., 1] = 255    
>>> iio.v3.imwrite("test.png", test_img, mode="LA")
>>> foo = iio.v3.imread("test.png")
>>> foo.shape                      
(512, 512, 2)
>>> np.allclose(foo, test_img)
True
```

**Closed by FirefoxMetzger** 2021-11-19 14:54 UTC
Labels: type: bug, plugin: pillow
