### ISSUE TITLE
Warning: the frame size for reading (864, 1080) is different from the source frame size (1792, 1080)

### ISSUE THREAD

**Issue by rodolpheg** [imageio/imageio#415] opened 2018-12-13 14:38 UTC
When reading some videos, I get this warning:

> WARNING:root:Warning: the frame size for reading (864, 1080) is
> different from the source frame size (1792, 1080).

and the exported image looks like this. As I try to export a frame to look at what is going on, I get this:

[![enter image description here][1]][1]

Here is my code:

    import imageio
    #imageio.plugins.ffmpeg.download()
    import numpy as np
    from PIL import Image, ImageFilter, ImageFont, ImageDraw
    
    reader = imageio.get_reader('movie.mkv')
    for i, im in enumerate(reader):
    	imag = Image.fromarray(im)
    	imag.save("image.jpg")

  [1]: https://i.stack.imgur.com/62cv7.jpg

It looks like the height and width are mixed up, while the image itself still tries to fit within the frame. Is this a known bug?

**Comment by almarklein** [comment] 2018-12-14 09:46
The warning is because it means that ffmpeg will have to do scaling, which may not be what you want.

I don't understand why the data is wrong. But I also don't know the input data or how you write `movie.mkv`, so its hard for me to point out what could be going wrong.

**Comment by almarklein** [comment] 2019-02-05 23:22
It is not unlikely that this has been fixed since #425. If not, is it possible to send a small video plus snippet to reproduce the error?

**Comment by almarklein** [comment] 2020-02-18 13:26
Closing this. Please re-open if the error persists.

**Closed by almarklein** 2020-02-18 13:26 UTC
Labels: plugin: ffmpeg, type: question
