### ISSUE TITLE
Animated GIF does not stop after specified number of loops

### ISSUE THREAD

**Issue by SteveDoyle2** [imageio/imageio#253] opened 2017-05-12 20:21 UTC
I'm trying to make an animated GIF that stops after all the pictures have been displayed.  In other words, I don't want any looping of the image.  Instead, it loops indefinitely.  

I looked at the documentation, which states that loop=0 makes it loop indefinitely, but presumably 1 should not loop at all and only play the images once.

http://imageio.readthedocs.io/en/latest/format_gif-pil.html?highlight=gif

Any suggestions?

The code I'm using is:

    import imageio
    png_filenames = ['1.png', '2.png', '3.png']
    gif_filename = 'model.gif'

    images = []
    for png_filename in png_filenames:
        images.append(imageio.imread(png_filename))
    duration = 0.25
    imageio.mimwrite(gif_filename, images, duration=duration,
                     loop=1)

I'm using Python 2.7-64 bit using Anaconda on Windows 10.

Some packages:
 - imageio 2.1.2
 - pillow 4.1.1

Attached is an example.

![model](https://cloud.githubusercontent.com/assets/1059417/26015557/5c70848c-3716-11e7-819e-fc2f861d60e0.gif)
![1](https://cloud.githubusercontent.com/assets/1059417/26015556/5c6e7cf0-3716-11e7-8df8-a23a8f128fa8.png)
![2](https://cloud.githubusercontent.com/assets/1059417/26015558/5c7427b8-3716-11e7-86fc-3b3adc9bf1d0.png)
![3](https://cloud.githubusercontent.com/assets/1059417/26015555/5c6d1b12-3716-11e7-8bd8-50e95ac4e1fb.png)

**Comment by almarklein** [comment] 2017-05-21 01:37
I think this is a duplicate of #237 which has been fixed in #237.

**Closed by almarklein** 2017-05-21 01:37 UTC
