### ISSUE TITLE
tifffile plugin

### ISSUE THREAD

**Issue by kuchi** [imageio/imageio#97] opened 2015-07-04 17:40 UTC
Add tifffile plugin for better tiff file support.

**Comment by kuchi** [comment] 2015-07-04 17:49
@Zulko & @blink1073 what would be the best approach for this plugin? 

1) Should a thin wrapper be made around the [pypi tifffile package](https://pypi.python.org/pypi/tifffile) and then tifffile added as a dependency for imageio? It could be an optional dependency and if tifffile is not installed then it could gracefully not load the thin wrapper.
2) Or should the code for tifffile be included in imagio.

I guess the risk of #1 is if tifffile gets updated and is not backwards compatible it could cause problems. But the downside is if updates are made to improve it then the user gets them and imageio does not lag behind. In fact, it looks like tifffile was updated recently.

The other advantage of #1 is imageio is pure python. Tifffile has some c code (although I think tifffile can gracefully fail and use a pure python implementation) . Having imageio import optionally import tifffile keeps imageio pure python.

**Comment by blink1073** [comment] 2015-07-04 18:21
I have already started work on the tifffile plugin.  My vote would be to include a current snapshot of the pure python part of tifffile and use that if a system version is not found.

**Comment by blink1073** [comment] 2015-07-04 20:48
PR is in #98.  This is also a duplicate of #30.

**Comment by almarklein** [comment] 2015-07-04 21:28
Closing as duplicate of #30 

(I also think the source code should go in imageio)

**Closed by almarklein** 2015-07-04 21:28 UTC
Labels: plugin: new, resolution: duplicate
