### ISSUE TITLE
ffmpeg mp4 mimsave with io.BytesIO() raises FileNotFoundError

### ISSUE THREAD

**Issue by Nik-Sch** [imageio/imageio#629] opened 2021-05-05 12:31 UTC
```python
out = io.BytesIO()
imageio.mimsave(out, allImages, 'mp4',  fps=1)
```
raises the following error for me (`allImages` is `List[PIL.Image.Image]`):

```python
[NULL @ 0x5fb7280] Unable to find a suitable output format for '/tmp/imageio_qg2ijcie'
/tmp/imageio_qg2ijcie: Invalid argument

Traceback (most recent call last):
  File [...]
    imageio.mimsave(out, allImages, 'mp4',  fps=1)
  File "/usr/local/lib/python3.9/site-packages/imageio/core/functions.py", line 419, in mimwrite
    written += 1
  File "/usr/local/lib/python3.9/site-packages/imageio/core/format.py", line 244, in __exit__
    self.close()
  File "/usr/local/lib/python3.9/site-packages/imageio/core/format.py", line 261, in close
    self.request.finish()
  File "/usr/local/lib/python3.9/site-packages/imageio/core/request.py", line 392, in finish
    with open(self._filename_local, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/imageio_qg2ijcie'
```

When saving directly as file instead of to an BytesIO object works as expected and save with `format='gif', duration=1` also works as expected.

**Comment by FirefoxMetzger** [comment] 2021-05-06 06:26
Interesting. Do you have an example file we can use as input to reproduce this problem?

I will likely not have the time to look into this today nor tomorrow, but I should be able to take a closer look next week :)

**Comment by Nik-Sch** [comment] 2021-05-06 07:50
Yes, sure, here is a MWE with the files I used :)
```python
from PIL import Image
import requests, io, imageio
urls = ['https://i.imgur.com/wj29HEg.png', 'https://i.imgur.com/cIhBi8H.png', 'https://i.imgur.com/749Mq6Q.png',
        'https://i.imgur.com/ZF3z3CU.png', 'https://i.imgur.com/raA1eI5.png', 'https://i.imgur.com/Ir88j8N.png']
allImages = map(lambda url: Image.open(io.BytesIO(requests.get(url).content)), urls)
out = io.BytesIO()
imageio.mimsave(out, allImages, 'mp4', fps=1) # doesn't work
imageio.mimsave(out, allImages, 'gif', duration=1) # works
imageio.mimsave('out.mp4', allImages, 'mp4', fps=1) # also works
```

**Comment by dearkafka** [comment] 2021-12-16 15:58
as 

```
imageio.mimsave(out, allImages, 'mp4', fps=1, output_params=["-f", "mp4"])
```

no longer works in '2.13.3'  is there a new way to write to io.BytesIO?

```
InitializationError: `FFMPEG` can not write to `<_io.BytesIO object at 0x7f27eed69678>`.
```

**Comment by FirefoxMetzger** [comment] 2021-12-16 19:25
@dearkafka This seems to be a symptom of https://github.com/imageio/imageio/issues/686. The gist is that there is a mismatch between what FFMPEG can actually read/write vs what the plugin claims FFMPEG can read/write. Once somebody volunteers to look into this issue the above should start working again.

A workaround would be to write into a temporary file and then read the raw file content into a BytesIO.

**Comment by FirefoxMetzger** [comment] 2022-04-14 13:47
Using the new pyav plugin the MWE works as expected:

```python
import imageio.v3 as iio
import numpy as np

urls = [
    "https://i.imgur.com/wj29HEg.png",
    "https://i.imgur.com/cIhBi8H.png",
    "https://i.imgur.com/749Mq6Q.png",
    "https://i.imgur.com/ZF3z3CU.png",
    "https://i.imgur.com/raA1eI5.png",
    "https://i.imgur.com/Ir88j8N.png",
]
allImages = map(lambda url: iio.imread(url, mode="RGB"), urls)
allImages = np.stack([x for x in allImages])
encoded = iio.imwrite(
    "<bytes>",
    allImages,
    format_hint=".mp4",
    plugin="pyav",
    fps=1,
    codec="h264",
)


# do something with the encoded bytes
```

Of course, this works when writing to `BytesIO` as well (assuming you actually need the stream-like behavior):

```python
import io

buffer = io.BytesIO()
iio.imwrite(
    buffer,
    allImages,
    format_hint=".mp4",
    plugin="pyav",
    fps=1,
    codec="h264",
)
```

The pyAV plugin will become available next week (during the next release cycle). With this, I think that we should be able to close this issue once v2.17 goes live.

---

Looking into this issue, I've also noticed that there is a bug in the plugin that causes it to sometimes write frames with the wrong timestamp, which messes up the video. This will be fixed in https://github.com/imageio/imageio/pull/787 (which will be part of the same release, if it gets merged this week).

**Closed** 2022-04-22 15:37 UTC
Labels: type: bug, plugin: ffmpeg
