### ISSUE TITLE
Install doesn't work for Python 2

### ISSUE THREAD

**Issue by teaglin** [imageio/imageio#519] opened 2020-03-13 21:33 UTC
Installing through pip doesn't work and if attempting to install directly from source the dependencies won't install either.

Collecting numpy (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/3a/5f/47e578b3ae79e2624e205445ab77a1848acdaa2929a00eeef6b16eaaeb20/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pillow (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/12/ad/61f8dfba88c4e56196bf6d056cdbba64dc9c5dfdfbc97d02e6472feed913/Pillow-6.2.2-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 790kB/s 
Collecting astropy (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/57/9d/69e74ec2eb8f6a2ac7c687ecac2703aabe3324dfafb83081780a96ce71ce/astropy-2.0.16-cp27-cp27mu-manylinux1_x86_64.whl (6.1MB)
    100% |████████████████████████████████| 6.1MB 277kB/s 
Collecting simpleitk (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/e1/6e/36cd6faefb7a6912d0abe60a8b60e4a8cf31ee5189979387d0a74361d56f/SimpleITK-1.2.4-cp27-cp27mu-manylinux1_x86_64.whl (42.5MB)
    100% |████████████████████████████████| 42.5MB 37kB/s 
Collecting imageio-ffmpeg (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/44/51/8a16c76b2a19ac2af82001985c80d3caca4c373528855cb27e12b39373fb/imageio-ffmpeg-0.3.0.tar.gz
imageio-ffmpeg requires Python '>=3.4' but the running Python is 2.7.17

**Comment by almarklein** [comment] 2020-03-13 22:09
Duplicate of #515. You can pin to imageio 2.6 as a workaround.

**Closed by almarklein** 2020-03-13 22:09 UTC
