### ISSUE TITLE
Poor performance of imwrite on PNG images

### ISSUE THREAD

**Issue by sciunto** [imageio/imageio#387] opened 2018-09-26 08:59 UTC
Hi,

I realized a significant slow down when I switched from cv2 to imageio of my IOs.

Here is a quick benchmark.
```
import imageio
print('imageio version ', imageio.__version__)
import cv2
print('cv2 version ', cv2.__version__)

from skimage import data
import os
import time

os.makedirs('imageio', exist_ok=True)
os.makedirs('cv2', exist_ok=True)


before = time.perf_counter()
for i in range(40):
    imageio.imwrite('imageio/' + str(i) + '.png', data.camera())
after = time.perf_counter()
print('imageio png: ', after - before)

before = time.perf_counter()
for i in range(40):
    cv2.imwrite('cv2/' + str(i) + '.png', data.camera())
after = time.perf_counter()
print('cv2 png: ', after - before)

before = time.perf_counter()
for i in range(40):
    imageio.imwrite('imageio/' + str(i) + '.jpg', data.camera())
after = time.perf_counter()
print('imageio jpg: ', after - before)

before = time.perf_counter()
for i in range(40):
    cv2.imwrite('cv2/' + str(i) + '.jpg', data.camera())
after = time.perf_counter()
print('cv2 jpg: ', after - before)

```

and the results

```
imageio version  2.4.1
cv2 version  3.4.3
imageio png:  8.024044567995588
cv2 png:  0.36481686899787746
imageio jpg:  0.41310937999514863
cv2 jpg:  0.23017822099791374
```

imageio is 16 times longer than opencv. I know there might be some differences in compression levels, but still...

Are you aware of that? Any hint?

Thanks.

**Comment by almarklein** [comment] 2018-09-26 09:12
Wow, that's interesting. Imageio uses Pillow for handling png, it would be interesting to see the performance of pure Pillow use as well...

**Comment by sciunto** [comment] 2018-09-26 12:11
I didn't check with pillow. 

Based on your remark (I didn't read imageio's code so far), I found this issue https://github.com/python-pillow/Pillow/issues/1211

With `compress_level=3` for imageio on png file.
```
imageio version  2.4.1
cv2 version  3.4.3
imageio png:  0.8065581480041146
cv2 png:  0.3645203570049489
imageio jpg:  0.4112834489933448
cv2 jpg:  0.22846891700464766
```

Now, for a zero compression level
```
imageio version  2.4.1
cv2 version  3.4.3
imageio png:  0.4493131430062931
cv2 png:  0.3619267880130792
imageio jpg:  0.41116392200638074
cv2 jpg:  0.23110742500284687
```

The ratios are closer for both compression levels. This might raise the question of the default compression level chosen in imageio. From level=9 to level=0, on this particular example, the size decreases from 128K to 112K.

To me, for a default value, a compression level less than 3 [to be tested on more images like colored vs bw] would be more valuable for most use case.

**Comment by almarklein** [comment] 2018-09-27 20:08
The default compression level in imageio is actually 9 :)  I think in most cases a properly compressed image is more important than speed. But that changes if you're batch-saving a lot of images. I don't think we'd need to change the default value, but we could document the implication better. Maybe an extra warning that if speed matters, lowering the `compress_level` helps.

**Comment by hmaarrfk** [comment] 2018-11-07 00:07
Only slightly I bet. I tried to save pngs in the past and the saving time
was maybe 4-10x that of BMP. I had large images though so it isn’t always
fair.

**Comment by tdoneal** [comment] 2019-06-16 18:52
+1, imageio.imwrite for .pngs is very slow.

I also noticed what seemed to be a slowdown _over time_ with repeated calls to imageio.imwrite() for pngs.  That makes no sense, because it should be stateless.  Nevertheless, detailed profiling revealed that it indeed was getting slower with each call.

Switching to cv2.imwrite() solved all my problems :)

**Comment by hmaarrfk** [comment] 2019-06-16 22:12
What backend does imageio use by default? It would be interesting to compare PIL vs freeimage. Is there a keyword argument that we can use to switch between the two?

Even setting the compression level down to 0 or 1, PIL???, seems to compress more than OpenCV, and is likely slower due to that.

**Comment by almarklein** [comment] 2019-06-17 09:16
`imwrite(..., format="PNG-FI ")`

**Comment by hmaarrfk** [comment] 2019-07-16 04:09
So these numbers fluctuate with different types of images, but it is pretty clear from some of my benchmarks that PIL and Freeimage's performance is pretty poor compared to opencv.

On something like a 4k x 2x image, opencv compresses in about 100 ms.
PIL takes somewhere between 700 - 1300 ms
FreeImage takes about the same.

These packages are installed from conda forge, on a pretty modern laptop processor. My guess is that Opencv likely uses AVX or SSE instructions, whereas PIL and FreeImage probably don't do the dispatching.

The final output size of opencv, PIL, and Freeimage for PNGs was roughly the same.
The exact size tends to depend on the exact image used.

It seems that DEFLATE is just slow. I remember when the iPhone came out, apple had spent alot of time optimize decompression of PNGs for their new displays.

https://serverfault.com/questions/160969/faster-zlib-alternatives

Maybe it is worth adding a opencv backend?

**Comment by hmaarrfk** [comment] 2019-07-20 16:47
Somebody rightfully pointed out that opencv default compression was 3, and imageio was 9.
I decided to explore this. These benchmarks are done with monochrome images. So if you use RGB, they are likely not applicable.
This reveals that the performance is much more similar than originally anticipated, at least for the specific images I tested against.

Can't really share the images just yet, we are working on it internally for the time being, but the original image size is about 10 M.

```
================================= =========================== =============================
--                                                    shape / image_type
--------------------------------- ---------------------------------------------------------
              backend               (2432, 4320) / image_0   (2432, 4320) / image_1
================================= =========================== =============================
           imageio-png:1              375±20ms     7.73M            345±20ms     6.70M
            opencv-png:1              368±30ms     7.76M            306±9ms      6.72M
          imageio-png-fi:1            358±10ms     7.76M            302±5ms      6.72M
      
           imageio-png:3              397±9ms      7.70M            403±8ms      6.62M
        opencv-png:3-default          386±10ms     7.72M            381±10ms     6.63M
    
           imageio-png:6              556±30ms     8.02M            739±10ms     7.11M
            opencv-png:6              526±9ms      7.85M            614±20ms     6.70M
          imageio-png-fi:6            529±20ms     7.85M            617±10ms     6.70M
      
       imageio-png:9-default          563±8ms      8.02M            757±9ms      7.11M
            opencv-png:9              520±8ms      7.85M            631±20ms     6.70M
      imageio-png-fi:9-default        534±9ms      7.85M            630±6ms      6.70M
================================= =========================== =============================
```

**Comment by almarklein** [comment] 2019-08-01 08:56
Thanks @hmaarrfk, that's really insightful!

**Comment by pwuertz** [comment] 2019-11-19 10:28
I'm so confused. My OpenCV 4.1.1 build is faster and more efficient when using default than it is when setting compression level 3. Tried setting any of the levels from 0-9, but I cannot reproduce what OpenCV is doing by default.
```
%timeit cv2.imwrite("test.png", img)
1.16 s ± 12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
# (11k x 11k) File 32.1M
%timeit cv2.imwrite("test.png", img, [cv2.IMWRITE_PNG_COMPRESSION, 3])
4.04 s ± 33.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
# (11k x 11k) File 36.1M
```

**Comment by OlofHarrysson** [comment] 2020-05-13 08:56
I'm seeing the same as you @pwuertz on opencv-python==4.2.0.32 via pip

**Comment by lhao0301** [comment] 2021-10-12 03:17
In [opencv-4.5.3 documents](https://docs.opencv.org/4.5.3/d8/d6a/group__imgcodecs__flags.html#gga292d81be8d76901bff7988d18d2b42acad2548321c69ab9c0582fd51e75ace1d0), it seems that when IMWRITE_PNG_COMPRESSION is passed, the strategy is changed. In default, IMWRITE_PNG_COMPRESSION is 1 and the strategy is IMWRITE_PNG_STRATEGY_RLE, which is the best speed setting?

**Comment by FirefoxMetzger** [comment] 2021-11-07 21:08
Thought I'd share the current results on my machine. I match the compression level between the libraries and I also refactored to stop measuring the data loading as well:

```
imageio version  2.10.3
cv2 version  4.5.4-dev
iio pillow png:  0.4974719000000001
iio FreeImage png:  0.5723408999999999
cv2 png:  0.3021674000000001
iio Pillow jpg:  0.06648860000000001
iio FreeImage jpg:  0.10420849999999993
cv2 jpg:  0.15684569999999987
```

<details>
<summary>Benchmark Code</summary>

```python
import imageio as iio
print('imageio version ', iio.__version__)
import cv2
print('cv2 version ', cv2.__version__)

import time
from pathlib import Path

base = Path("bench")
iio_dir = (base / "imageio")
cv2_dir = (base / "cv2")

iio_dir.mkdir(parents=True, exist_ok=True)
cv2_dir.mkdir(parents=True, exist_ok=True)

img = iio.v3.imread("imageio:camera.png", plugin="pillow", mode="RGB")

before = time.perf_counter()
for i in range(40):
    iio.v3.imwrite(iio_dir / f"{i}.png", img, plugin="pillow", compress_level=1)
after = time.perf_counter()
print('iio pillow png: ', after - before)

before = time.perf_counter()
for i in range(40):
    iio.imwrite(iio_dir / f"{i}.png", img, format="PNG-FI", compression=1)
after = time.perf_counter()
print('iio FreeImage png: ', after - before)

before = time.perf_counter()
for i in range(40):
    cv2.imwrite(str(cv2_dir / f"{i}.png"), img)
after = time.perf_counter()
print('cv2 png: ', after - before)

before = time.perf_counter()
for i in range(40):
    iio.v3.imwrite(iio_dir / f"{i}.jpg", img, plugin="pillow")
after = time.perf_counter()
print('iio Pillow jpg: ', after - before)

before = time.perf_counter()
for i in range(40):
    iio.imwrite(iio_dir / f"{i}.jpg", img, format="JPEG-FI")
after = time.perf_counter()
print('iio FreeImage jpg: ', after - before)

before = time.perf_counter()
for i in range(40):
    cv2.imwrite(str(cv2_dir / f"{i}.jpg"), img)
after = time.perf_counter()
print('cv2 jpg: ', after - before)


```

</details>

writing PNGs is currently 66% slower than cv2, but JPEG writing is about 2.5x faster o.O Could anyone confirm these results?

**Comment by FirefoxMetzger** [comment] 2022-04-18 13:01
This should get resolved with the introduction of the opencv plugin developed here: https://github.com/imageio/imageio/pull/791. 

Essentially, if you specify that you wish to write via opencv (`imwrite(..., plugin="opencv")`) you will get similar performance to "native" openCV:

```
imageio version  2.18.0
cv2 version  4.5.5
iio pillow png:  0.5217077
iio FreeImage png:  0.6019517
iio PyAV png:  1.5066044
iio cv2 png:  0.3105000000000002
cv2 png:  0.32240139999999995
```

<details>
<summary>Code for the benchmark</summary>

```python
import imageio as iio

print("imageio version ", iio.__version__)
import cv2

print("cv2 version ", cv2.__version__)

import time
from pathlib import Path

base = Path("bench")
iio_dir = base / "imageio"
cv2_dir = base / "cv2"

iio_dir.mkdir(parents=True, exist_ok=True)
cv2_dir.mkdir(parents=True, exist_ok=True)

img = iio.v3.imread("imageio:camera.png", plugin="pillow", mode="RGB")

before = time.perf_counter()
for i in range(40):
    iio.v3.imwrite(iio_dir / f"{i}.png", img, plugin="pillow", compress_level=1)
after = time.perf_counter()
print("iio pillow png: ", after - before)

before = time.perf_counter()
for i in range(40):
    iio.imwrite(iio_dir / f"{i}.png", img, format="PNG-FI", compression=1)
after = time.perf_counter()
print("iio FreeImage png: ", after - before)

before = time.perf_counter()
for i in range(40):
    iio.v3.imwrite(
        iio_dir / f"{i}.png", img, plugin="pyav", codec="png", is_batch=False
    )
after = time.perf_counter()
print("iio PyAV png: ", after - before)

before = time.perf_counter()
for i in range(40):
    iio.v3.imwrite(iio_dir / f"{i}.png", img, plugin="opencv")
after = time.perf_counter()
print("iio cv2 png: ", after - before)

before = time.perf_counter()
for i in range(40):
    img_cv2 = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    cv2.imwrite(str(cv2_dir / f"{i}.png"), img_cv2)
after = time.perf_counter()
print("cv2 png: ", after - before)

```

</details>

**Comment by FirefoxMetzger** [comment] 2022-12-19 19:44
I will close this issue as the only way to improve this even further is to make improvements to pillow's PNG writer, which should be done in the upstream repo :)

Throughout this discussion, the writing speed for PNG in pillow has improved ~16x, however, it is still 40% slower than OpenCV. 

If you _need_ every last bit of performance but still want ImageIOs API, there is also now the option to use OpenCV as a backend for ImageIO via `plugin="opencv"`. Doing so is about 3% slower than pure OpenCV so should be close enough :)

**Closed by FirefoxMetzger** 2022-12-19 19:44 UTC
Labels: type: question, plugin: pillow
