### ISSUE TITLE
EXR-FI can not handle the given uri

### ISSUE THREAD

**Issue by sharktacos** [imageio/imageio#869] opened 2022-08-26 05:49 UTC
Have the following in the Python Script Editor of Maya2022

`import imageio.v3 as iio
import imageio_freeimage
path = '/path/to/image.exr'
img = iio.imread(path, plugin="EXR-FI")`

getting the following error from the last line:
`# Error: OSError: file /Applications/Autodesk/maya2022/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/imageio/core/imopen.py line 165: `EXR-FI` can not handle the given uri. # `

This is a 16-bit half float OpenEXR with PIZ compression.

**Comment by FirefoxMetzger** [comment] 2022-08-26 08:51
Interesting. I didn't know that maya allows you to write python scripts to automate your workflow. Did you have to install ImageIO yourself or does it come with ImageIO preinstalled?

On the note of EXR files, there are currently three backends that support reading this format: FreeImage (default), pyav, and OpenCV. `EXR-FI` indicates that you are reading the image using FreeImage. A comment source of error here is that some users forget to download the freeimage binary (see the [note in the docs](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.freeimage.html)). Did you download it? Beyond that it's hard to say what's happening without having access to the problematic file (or a variant of it to reproduces the issue). Are you able to share the file so that I can take a look? Also, could you share the full stack trace of the error?

**Comment by sharktacos** [comment] 2022-08-26 16:27
Had to install it myself. Maya provides a wrapper to do this using pip in a terminal. So to install imageio I did `mayapy -m pip install imageio` and to install freeimage `mayapy -m pip install imageio-freeimage`. Everything else I do inside Maya in its internal Python console (the Script Editor), which does not allow me to run  `imageio.plugins.freeimage.download()` which is why I was hoping that the above pip install of freeimage from the repo here was an alternative way to get it working.

Since I'm just running that little snippet of code in my OP in Maya's Python terminal, there is no stack trace. Just that one error line. Since it came out kind of wonky above here it is again:

import imageio.v3 as iio
import imageio_freeimage
path = '/path/to/image.exr' 

all this works fine. This next line throws the error:

img = iio.imread(path, plugin="EXR-FI")

I suspect that the issue is not with EXR files, but more with how I have freeimage reading _any_ file. For example if I read in a PNG to imageio strait with `img = iio.imread(path)` is reads it just fine. However if I read that PNG with the freeimage plugin like so `img = iio.imread(path, plugin="PNG-FI")` I get that same error as I do with the EXR: "`PNG-FI` can not handle the given uri." 

Here a link to the EXR and PNG files I'm using. They are just flat gray:
https://github.com/sharktacos/VFX-software-prefs/tree/main/test_images/

**Comment by FirefoxMetzger** [comment] 2022-08-26 19:39
> Everything else I do inside Maya in its internal Python console (the Script Editor), which does not allow me to run imageio.plugins.freeimage.download() which is why I was hoping that the above pip install of freeimage from the repo here was an alternative way to get it working.

Ah, that explains where the problem comes from. It is indeed due to the missing FreeImage binary on your system.

`imageio-freeimage` is a currently in-flight project (https://github.com/imageio/imageio/pull/831) to migrate the plugin into its own repository ... it is not yet finished. It also is a copy of what is here, so you will still have to download the binary manually. I've been dedicating some spare time to bundling it with `imageio-freeimage` (https://github.com/imageio/imageio-freeimage/pull/3), but I still have issues to fix for some python variants on windows and the MacOS builds are also missing still.

Could you share some more details on how it is impossible to run `imageio.plugins.freeimage.download()` or what happens if you do? I would have thought you can simply make it part of your script (it won't redownload if the binary already exists) or write a small script that you run once to get the file. You can also manually download it, or use the one you get from your package manager, but those options are less desirable so maybe we can see if there is a better one first.

> For example if I read in a PNG to imageio strait with img = iio.imread(path) is reads it just fine. However if I read that PNG with the freeimage plugin like so img = iio.imread(path, plugin="PNG-FI") I get that same error as I do with the EXR: "PNG-FI can not handle the given uri."

That's correct, because reading PNG by default uses pillow instead of FreeImage. Since you are missing the binary, every call to use FreeImage will fail for that reason.

Also, I tried the EXR file and i don't have any issues reading it on my system when using FreeImage:

```python
>>> import imageio.v3 as iio
>>> img = iio.imread("https://github.com/sharktacos/VFX-software-prefs/blob/main/test_images/flat_bmp.exr?raw=true")
>>> img.shape
(2048, 2048)
>>> img.dtype
dtype('float32')
>>> img = iio.imread("https://github.com/sharktacos/VFX-software-prefs/blob/main/test_images/flat_bmp.exr?raw=true", plugin="EXR-FI")  
>>> img.shape
(2048, 2048)
```

**Comment by sharktacos** [comment] 2022-08-27 00:26
Thanks that's helpful. On a Mac when I run `imageio.plugins.freeimage.download()` I get the error:

`Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>`

I tried instead doing it on Windows, and it downloads the file and I can then read the EXR! 

I see that it's downloading the DLL to `C:\User\[USER NAME]\AppData\Local\` should I move it to someplace else or is that where it officially needs to be?

**Comment by FirefoxMetzger** [comment] 2022-08-27 04:54
> [...] SSL: CERTIFICATE_VERIFY_FAILED [...]

Ah, that is a problem I've seen before and it could be the same as https://github.com/imageio/imageio/issues/500 . It could be possible to fix by following the suggestions in [this SO answer](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify/42098127#42098127), though I don't know how well this translates to the python version that Maya gives you.

> I see that it's downloading the DLL to C:\User\[USER NAME]\AppData\Local\ should I move it to someplace else or is that where it officially needs to be? Ideally I'd like it to be where all users can get to it.

You _can_ move the file around and set the environment variable `IMAGEIO_FREEIMAGE_LIB` to point to the new location. It's not very common though and goes a bit against the grain of modern python, which tries to isolate installed packages between users and projects and avoids sharing as much as possible. This way, if you update your dependency in one project to a new version, you reduce the risk of breaking another. So while you _can_ place the binary somewhere else it's usually not recommended.

**Comment by sharktacos** [comment] 2022-08-27 18:39
Maya installs imageio in its Python site-packages folder, so I think in this case it makes sense to have the DLL in there too. Setting the environment variable to point to this works great.

For Mac, it appears that the `Install Certificates.command` is not included in Maya's Python3.7, so I instead downloaded the DLL file (.dylib) from the https://github.com/imageio/imageio-binaries repo and pointed the environment variable to it. 

Everything is working now on both Windows and Mac. Thanks so much for all your help!

**Comment by FirefoxMetzger** [comment] 2022-08-27 18:53
That's great, glad that it worked :) I will close this issue as resolved but feel free to comment if there is more and we can re-open as needed.

**Closed by FirefoxMetzger** 2022-08-27 18:53 UTC
Labels: type: bug, plugin: freeimage
