### ISSUE TITLE
Support for freezing

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#684] opened 2021-11-17 08:30 UTC
In a recent change, the plugins are imported dynamically. This poses a problem when freezing an app that contains imageio. See the discussion below.

_Originally posted by @almarklein in https://github.com/imageio/imageio/pull/680#discussion_r748429429_

We should probably:
* Make a note about this in the docs.
* For PyInstaller we can use its recent hook system. See wgpu-py for an example (links in the discussion linked above).

**Comment by hanselda** [comment] 2021-12-07 06:49
I am surprised by this behavior when installing the new imageio version that the exe generated by pyinstaller does not work anymore. Currently I revert back to version 2.10.5.

**Comment by FirefoxMetzger** [comment] 2021-12-07 08:08
@hanselda Thanks for letting us know. Could you describe how things are breaking? That way, we can figure out what to adjust to make it work again.

In particular, could you give us a small example of what you are doing so we can try to reproduce it locally on our machines?

**Comment by hanselda** [comment] 2021-12-07 15:16
Python 3.9.8 64-bit
Windows 10

venv 
requirements.txt:
altgraph==0.17.2
future==0.18.2
imageio==2.13.2
numpy==1.21.4
pefile==2021.9.3
Pillow==8.4.0
pyinstaller==4.7
pyinstaller-hooks-contrib==2021.4
pywin32-ctypes==0.2.0

content of test.py
`
from imageio import imread
img = imread("test.tif")
print(img.shape)
input()
`

There is a image file "test.tif" in the same folder as test.py. Running the python script directly will print the shape of the image, which is the expected behavior. Now use pyinstaller to create an exe "pyinstaller test.py". Running the exe will give the following exception:
Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "imageio\core\functions.py", line 159, in imread
  File "imageio\core\imopen.py", line 277, in imopen
ValueError: Could not find a backend to open `test.tif`` with iomode `ri`.
Based on the extension, the following plugins might add capable backends:
  TIFF:  pip install imageio[tifffile]
  pillow:  pip install imageio[pillow]
  TIFF-PIL:  pip install imageio[pillow]
  TIFF-FI:  pip install imageio[freeimage]
  FEI:  pip install imageio[feisem]
  ITK:  pip install imageio[simpleitk]
  GDAL:  pip install imageio[gdal]
[10336] Failed to execute script 'test' due to unhandled exception!

**Comment by richardsheridan** [comment] 2022-02-23 19:33
I hit this too. This is almost certainly due to the new lazy-loading in #680. That kind of thing requires a more extensive hook than is currently found in pyinstaller-hooks-contrib:

https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/ea3fc4827efae5a9befb304a3c3e12ffc622657f/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-imageio.py#L1-L17

An example of how to approach a fix for this might be:

https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/ea3fc4827efae5a9befb304a3c3e12ffc622657f/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py#L26-L36

**Comment by FirefoxMetzger** [comment] 2022-02-23 20:43
The reason I never attempted to fix this is that I have 0 knowledge about freezing or pyinstaller for that matter. As a result, I'm hoping for a motivated volunteer to take charge and implement a fix. I'm happy to review and support the effort to the extent I can, but won't be able to spearhead it.

From what I've understood so far pyinstaller will import the package and track what modules are imported in the process? In that case, a workaround *might* be to include the desired plugin modules explicitly at the beginning of your script (e.g., `import imageio.plugins.pillow`).

**Comment by richardsheridan** [comment] 2022-02-23 21:54
@FirefoxMetzger Yeah, this is not really your problem to fix, as the burden should fall on pyinstaller or its users rather than package maintainers.

imageio's lazy loading is an interesting case as (1) these plugins are exactly the kind of thing that pyinstaller tries desperately to avoid collecting to minimize package size and (2) these plugins are super lightweight and won't bloat the installer. It is therefore questionable whether a hook is actually appropriate.

A little digging shows that another simple workaround that doesn't touch the code is to add a command line switch when calling pyinstaller:

`pyinstaller --collect-submodules imageio <entry_script.py>`

Alternatively, if a user really wants to limit the plugins used:

`pyinstaller --hidden-import imageio.plugins.<pillow, for example> <entry_script.py>`

Given these (and your) workarounds, I think you should feel free to close the issue. I'll possibly submit a hook in the future myself.

**Comment by FirefoxMetzger** [comment] 2022-02-24 08:09
> (2) these plugins are super lightweight and won't bloat the installer.

Don't forget about transient dependencies. Most plugins delegate the heavy lifting to 3d party packages (which are optional dependencies). For example our `ffmpeg` plugin requires ffmpeg, or `freeimage` requires - well - the FreeImage library. If you need it, you need it, but otherwise there is no harm in pruning those binaries.

Another point is wide-range platform support (which is ultimately why we now lazy-load plugins). Supporting individual plugins across all major OSes is one thing, supporting an arbitrary combination of them is another. Most users only use a few plugins (1 or 2), so lazy-loading helps mitigate this combinatoric explosion.

> A little digging shows that another simple workaround that doesn't touch the code is to add a command line switch when calling pyinstaller [...] Given these (and your) workarounds, I think you should feel free to close the issue. I'll possibly submit a hook in the future myself.

That sounds awesome! It's good to hear that there are existing solutions to the problem. The next step to think about now is the discoverability of those solutions. I wonder if it would be good to leave a note in our docs somewhere (or perhaps the pyinstaller docs if applicable) to let users of pyinstaller know that they have to explicitly import plugins and what their options are. 

What would be even better is if we could check if pyinstaller is scanning for dependencies, see if any plugins were imported, and raise a warning if not. I guess that is what hooks would be for?

**Comment by richardsheridan** [comment] 2022-02-24 14:42
> Don't forget about transient dependencies. Most plugins delegate the heavy lifting to 3d party packages (which are optional dependencies). For example our ffmpeg plugin requires ffmpeg, or freeimage requires - well - the FreeImage library. If you need it, you need it, but otherwise there is no harm in pruning those binaries.

Since pyinstaller never invokes pip or any other package manager, the "correct" way, in my experience, to avoid these transient dependencies is to make sure that they are not installed in the virtual environment. So to get `tifffile` but not `ffmpeg` simply do `pip install imageio[tifffile]` in a fresh venv... assuming all of the `imageio` plugin modules are available to be lazy-loaded!

Therefore I don't think runtime checks and warnings for pyinstaller are going to be valuable. I do like the idea of a paragraph or two in the imageio docs describing workarounds and environment/dependency management for freezing.

**Comment by FirefoxMetzger** [comment] 2022-02-24 18:53
> Therefore I don't think runtime checks and warnings for pyinstaller are going to be valuable.

Yes, at runtime it will be to late to change anything. I was thinking at packaging time (whichever the correct lingo is; in C I would say during compile time), but I'm not sure if pyinstaller allows us to discover this.

>  I do like the idea of a paragraph or two in the imageio docs describing workarounds and environment/dependency management for freezing.

Sure, we can certainly add documentation on this. @richardsheridan Since you faced the problem, where inside the docs would you have searched for this info? (I'm hoping to identify an intuitive place where this will live.)

**Comment by richardsheridan** [comment] 2022-02-25 02:45
I humbly suggest that you could break off the 

- [Command Line Scripts](https://imageio.readthedocs.io/en/stable/getting_started/cmdlinescripts.html)
- [Environment Variables](https://imageio.readthedocs.io/en/stable/getting_started/envvariables.html)
- [Upgrading to ImageIO](https://imageio.readthedocs.io/en/stable/getting_started/index.html#upgrading-to-imageio)

sections from "getting started" into something like "advanced usage" and in that new section, add a page about freezing/packaging/distributing.

**Comment by FirefoxMetzger** [comment] 2022-02-25 04:46
Yep, I like that idea. We can rename the "Getting Started" page into "User Guide" and have both a "Getting Started" section in there as well as a section on "Other Usage" which could look like you suggested:

- Command Line Scripts
- Environment Variables
- the two sections  from Upgrading to ImageIO
- Freezing ImageIO (new section)

@richardsheridan Would you like to contribute this change (I will help you get started and review), or should I do it?

**Closed** 2022-02-27 15:49 UTC
Labels: type: bug, building/installing
