### ISSUE TITLE
Can't always read from url

### ISSUE THREAD

**Issue by Tadaboody** [imageio/imageio#335] opened 2018-04-14 14:31 UTC
Running the following code snippet

```python
#test.py
import imageio  
gif = imageio.mimread("""https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif""")
print(gif.shape)
```   
![The gif](https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif)

results in an error.  
full traceback:  
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    gif = imageio.mimread("https://media.giphy.com/media/3o6Zth3OnNv6qDGQ9y/giphy.gif")
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/imageio/core/functions.py", line 281, in mimread
    reader = read(uri, format, 'I', **kwargs)
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/imageio/core/functions.py", line 129, in get_reader
    return format.get_reader(request)
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/imageio/core/format.py", line 168, in get_reader
    return self.Reader(self, request)
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/imageio/core/format.py", line 217, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/imageio/plugins/pillowmulti.py", line 57, in _open
    return PillowFormat.Reader._open(self)
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/imageio/plugins/pillow.py", line 131, in _open
    if hasattr(self._im, 'n_frames'):
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/PIL/GifImagePlugin.py", line 96, in n_frames
    self.seek(self.tell() + 1)
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/PIL/GifImagePlugin.py", line 128, in seek
    self._seek(f)
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/PIL/GifImagePlugin.py", line 158, in _seek
    self.fp.seek(self.__offset)
  File "/home/tomer/pet-projects/RevBot/venv/lib/python3.5/site-packages/imageio/core/request.py", line 511, in seek
    ori_seek(i, mode)
io.UnsupportedOperation: seek
```

Run on python 3.5 on Ubuntu 16.04 LTS

**Comment by almarklein** [comment] 2018-04-16 07:46
Apparently, Pillow uses `seek` for gif (like it does for jpg) and `seek` is not possible for url requests. For JPG we do a [workaround](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow.py#L400) by downloading the whole image beforehand. I am less sure whether this is a good idea for gif, though; it would be ok for small gifs, but a user may think that a large gif is streamed from the web, while in fact it is not ...

You can always do
```py
from urllib.request import urlopen
import imageio

url = "https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif"
blob = urlopen(url).read()
ims = imageio.imread(blob, '.gif')
```

**Comment by almarklein** [comment] 2018-04-16 07:47
Perhaps we can add an argument to force downloading, and mention this option when we get a seek error.

**Comment by Tadaboody** [comment] 2018-04-16 19:00
how about something like
```python
import requests
url = """"https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif""""
download_generator = requets.get(url,stream=true)
chunk_size = 128
for chunk in download.iter_content(chunk_size=chunk_size):
    yield imageio.imread(chunk,'.gif')
```
to stream the gif? 
will there be problems with using imread on parts of the gif?

**Comment by Tadaboody** [comment] 2018-04-17 09:04
Is there a way to look at the string of chunks so far and cut it to the last valid frame?
if so you could do something like
import requests
import imageio
url = """"https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif""""
download_generator = requets.get(url,stream=true)
chunk_size = 128
furthest_frame_yielded = 0
chunks_so_far = list()
for chunk in download.iter_content(chunk_size=chunk_size):
    chunks_so_far.extend(chunk)
    gif_so_far = imageio.imread(chunks_so_far,'.gif') #Array until the last valid frame in chunks_so_far
    yield gif_so_far[furthest_frame_yielded:]
    furthest_frame_yielded = len(gif_so_far)

**Comment by almarklein** [comment] 2018-04-18 18:35
I don't think that will work either. Pillow just seems to want the whole file...

**Comment by almarklein** [comment] 2018-09-03 19:59
Added docs regarding this issue in #372. I made an attempt to bend Pillow to my will and have it avoid using seek, but that did not work, unfortunately.

**Comment by almarklein** [comment] 2018-09-03 20:01
In theory, its possible to detect this issue, and have imageio automatically download the file. But as I said, that might raise false expectations so I am a bit hesitant. Leaving this issue open to represent that option though ...

**Comment by almarklein** [comment] 2019-02-06 10:12
Noting: several plugins by now use `Request.get_local_file()` when reading from http/https, so this should be resolved for most cases. But not all, because it depends on whether the plugin needs seek.

**Comment by almarklein** [comment] 2020-02-18 15:25
Closing as duplicate of #505

**Closed by almarklein** 2020-02-18 15:25 UTC
Labels: plugin: pillow, type: question
